schemathesis/schemathesis

docs/changelog.rst
src/schemathesis/extra/pytest_plugin.py
test/schemas/test_parametrization.py

Handle errors during tests collection / execution as failures

---

.github/workflows/build.yml

To avoid waiting for the black package to be installed every time

actions: Use kiwicom/black image

---

src/schemathesis/extra/pytest_plugin.py
src/schemathesis/generator.py
src/schemathesis/parametrizer.py
src/schemathesis/schemas.py
test/schemas/test_parametrization.py
test/test_parametrizer.py
test/test_schemas.py

To fix cases discovered by mutmut

Stricter tests & refactoring

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/models.py
src/schemathesis/schemas.py
src/schemathesis/types.py
test/conftest.py
test/data/simple_openapi.yaml
test/test_parameters.py

Resolves https://github.com/kiwicom/schemathesis/issues/21

Add support for cookie parameter in OpenAPI 3.0

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/models.py
src/schemathesis/schemas.py
src/schemathesis/types.py
test/conftest.py
test/test_parameters.py

Resolves https://github.com/kiwicom/schemathesis/issues/6

Add formData parameter in SwaggerV20 schema

---

poetry.lock
pyproject.toml
src/schemathesis/runner.py
test/conftest.py
test/test_runner.py
tox.ini

Initial draft on the logic, that will execute certain checks against some app
TODO:
In the future, it could be also WSGI apps, so `requests` might be optional. Also, some parts could be done asynchronously (tests itself could be run in parallel if there are no restrictions from the hypothesis side), but I am not sure how to implement it better :(

[WIP] Test executor

---

docs/changelog.rst
src/schemathesis/models.py
test/test_runner.py

Update test executor

---

docs/changelog.rst
src/schemathesis/schemas.py
test/test_dereferencing.py

Handle x-nullable

---

test/test_runner.py

Use `aiohttp_unused_port` to fix parallel run

---

docs/changelog.rst
src/schemathesis/loaders.py
src/schemathesis/schemas.py
src/schemathesis/types.py
src/schemathesis/utils.py
test/conftest.py
test/test_filters.py

Add support for filtering in loaders

---

test/test_common_parameters.py
test/test_dereferencing.py
test/test_filters.py
test/test_lazy.py
test/test_parametrization.py
test/test_required.py

The issue is that changing these lines didn't make the tests fail:
https://github.com/kiwicom/schemathesis/blob/master/src/schemathesis/schemas.py#L51
https://github.com/kiwicom/schemathesis/blob/master/src/schemathesis/schemas.py#L53

Make tests more strict to address issues found by mutmut

---

docs/changelog.rst
src/schemathesis/schemas.py
test/test_petstore.py

Handle type "file" for Swagger 2.0

---

src/schemathesis/lazy.py
test/test_lazy.py

Update filtration for LazySchema

---

README.rst
docs/changelog.rst
poetry.lock
pyproject.toml
src/schemathesis/commands.py
src/schemathesis/runner.py
test/conftest.py
test/test_commands.py
tox.ini

- Fix: https://github.com/kiwicom/schemathesis/issues/30

Add CLI tool for running schemathesis test cases

---

docs/changelog.rst
poetry.lock
pyproject.toml
src/schemathesis/_hypothesis.py
src/schemathesis/extra/pytest_plugin.py
test/conftest.py
test/test_async.py
tox.ini

A straightforward approach, I'm not completely sure about corner cases

Add support for coroutine-based tests. Resolves #121

---

test/test_runner.py

Add a regression test case for runner stopping on the first failure

---

src/schemathesis/runner.py
test/cli/test_commands.py
test/test_compat.py
test/test_parameters.py

Extra assertions found by mutmut + simplification of assertions re-raisung in the `runner` module

Stricter tests

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
test/cli/test_commands.py

Add HTTP Digest Auth support

---

README.rst
docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
src/schemathesis/cli/options.py
src/schemathesis/runner.py
src/schemathesis/utils.py
test/cli/test_callbacks.py
test/cli/test_commands.py
test/cli/test_options.py
test/test_runner.py

Add support for Hypothesis settings in CLI & Runner.

---

README.rst
docs/changelog.rst
src/schemathesis/__init__.py
src/schemathesis/_compat.py
src/schemathesis/_hypothesis.py
src/schemathesis/models.py
test/test_hypothesis.py

Add ability to register strategies for custom string formats

---

docs/changelog.rst
src/schemathesis/lazy.py
src/schemathesis/loaders.py
test/test_lazy.py

Make LazySchema accept filters

---

.github/workflows/build.yml

Currently it runs only for direct push to this repository, but not for PR from forks.

Run GitHub Actions on pull request

---

src/schemathesis/_hypothesis.py
test/test_hypothesis.py

Speedup Case generation

---

docs/changelog.rst
src/schemathesis/runner.py

Set default deadline to 500ms

---

README.rst
docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/loaders.py
src/schemathesis/models.py
src/schemathesis/runner.py
src/schemathesis/schemas.py
src/schemathesis/utils.py
test/test_loaders.py
test/test_models.py
test/test_parametrization.py

Automatically detect base URL when possible in schemas

---

docs/changelog.rst
src/schemathesis/__init__.py
src/schemathesis/constants.py
src/schemathesis/loaders.py
src/schemathesis/runner/__init__.py
test/app.py
test/conftest.py
test/test_loaders.py
test/test_package.py
test/test_runner.py

Use Schemathesis UserAgent during schema loading

---

.github/workflows/build.yml

Fix CI jobs repeat on PR edit

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/test_hypothesis.py

Fix generation of invalid headers values in ``Case.headers``

---

src/schemathesis/_hypothesis.py

Leftover from a wrong test setup

Remove unused code

---

src/schemathesis/cli/__init__.py
src/schemathesis/filters.py
src/schemathesis/lazy.py
src/schemathesis/loaders.py
src/schemathesis/schemas.py
test/cli/test_commands.py
test/test_filters.py
test/test_lazy.py

WIP #134 Still don't know how to fix this test :-( 
==================================== ERRORS ====================================
_____________________ ERROR collecting test_tag_filter.py ______________________
/home/mnalband/schemathesis/.tox/py37/lib/python3.7/site-packages/schemathesis/extra/pytest_plugin.py:51: in collect
item for endpoint in self.schemathesis_case.get_all_endpoints() for item in self._gen_items(endpoint)
/home/mnalband/schemathesis/.tox/py37/lib/python3.7/site-packages/schemathesis/extra/pytest_plugin.py:51: in <listcomp>
item for endpoint in self.schemathesis_case.get_all_endpoints() for item in self._gen_items(endpoint)
/home/mnalband/schemathesis/.tox/py37/lib/python3.7/site-packages/schemathesis/schemas.py:116: in get_all_endpoints
parameters = …

Filter Swagger/OpenAPI operations by tag

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/output.py
src/schemathesis/schemas.py
test/cli/test_commands.py

[WIP] Interactive CLI output

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/loaders.py
test/cli/test_commands.py

Fix error message if schema is not found in CLI

---

src/schemathesis/cli/__init__.py
src/schemathesis/cli/output.py
src/schemathesis/models.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/events.py
test/cli/test_commands.py
test/cli/test_output.py
test/test_runner.py

[WIP] CLI refactoring

---

docs/changelog.rst
src/schemathesis/cli/output.py
src/schemathesis/models.py
test/cli/test_commands.py

Fix CLI failing on empty checks list

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/models.py
test/test_common_parameters.py
test/test_dereferencing.py
test/test_direct_access.py
test/test_hypothesis.py
test/test_models.py
test/test_parameters.py
test/test_parametrization.py
test/test_required.py
test/test_runner.py

Do not send any payload with GET requests.

---

docs/changelog.rst
src/schemathesis/cli/output.py
src/schemathesis/models.py
src/schemathesis/runner/__init__.py
src/schemathesis/utils.py
test/cli/test_commands.py

Show exceptions in a separate section of the CLI output

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/test_compat.py

Fix compatibility with Hypothesis 4.42.4+

---

docs/changelog.rst
src/schemathesis/runner/__init__.py
src/schemathesis/utils.py
test/app.py
test/cli/test_commands.py

Change error message for cases when it is not possible to satisfy schema parameters.

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/exceptions.py
src/schemathesis/extra/pytest_plugin.py
src/schemathesis/lazy.py
src/schemathesis/models.py
src/schemathesis/runner/__init__.py
src/schemathesis/schemas.py
test/app.py
test/cli/test_commands.py
test/test_lazy.py
test/test_parametrization.py

Option to suppress schema errors

---

docs/changelog.rst
src/schemathesis/cli/output.py
src/schemathesis/models.py
src/schemathesis/runner/__init__.py
src/schemathesis/utils.py
test/app.py
test/cli/test_commands.py

Display flaky errors only in the "ERRORS" section and improve CLI output

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/runner/__init__.py
test/cli/test_commands.py

An option to configure request timeout for CLI / Runner.

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/output.py
src/schemathesis/utils.py
test/cli/test_commands.py

Display a proper error message when schema is not available in CLI / Runner

---

docs/changelog.rst
src/schemathesis/cli/output.py
src/schemathesis/models.py
test/cli/test_output.py
test/test_models.py

Show code to reproduce errors in CLI output

---

docs/changelog.rst
src/schemathesis/cli/output.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/events.py
test/cli/test_commands.py
test/cli/test_output.py

Add total running time to the CLI output

---

docs/changelog.rst
src/schemathesis/models.py
test/test_models.py

Fix handling cookies in ``Case.call``

---

docs/changelog.rst
src/schemathesis/cli/output.py
src/schemathesis/loaders.py
src/schemathesis/schemas.py
test/app/__init__.py
test/conftest.py
test/test_schemas.py

Add extra information to the CLI output: schema address, spec version and base url

---

docs/changelog.rst
src/schemathesis/__init__.py
src/schemathesis/_hypothesis.py
test/test_hypothesis.py

Generate binary data for `format=binary`

---

docs/changelog.rst
src/schemathesis/cli/output.py
test/cli/test_commands.py

Fix error that happens when there are no success checks in the statistic in CLI

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
test/cli/test_callbacks.py
test/cli/test_commands.py

CLI: Support file paths in `schema` argument

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/test_common_parameters.py
test/test_hypothesis.py

Raise an error if schema has body for GET requests

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/runner/__init__.py
test/cli/test_commands.py
test/test_runner.py

Fix custom base URL handling in CLI / Runner

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/schemas.py
test/test_direct_access.py

Make method names case insensitive during direct schema access

---

docs/changelog.rst
src/schemathesis/schemas.py
test/data/simple_openapi.yaml
test/test_schemas.py

Support OpenAPI 3.0 base paths

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/test_hypothesis.py

Add support for `format: byte`

---

.github/workflows/scheduled.yml

Fix mutmut CI job

---

README.rst
test/conftest.py
test/test_unittest.py

Add tests for `unittest` & update documentation

---

README.rst
docs/changelog.rst
src/schemathesis/cli/__init__.py
test/app/__init__.py
test/app/handlers.py
test/cli/test_commands.py
test/conftest.py

The next step would be to add a way to register custom checks, will do in a separate PR
Resolves #147
TODO:

Add pre-run CLI hook

---

src/schemathesis/cli/__init__.py
test/cli/test_commands.py
test/conftest.py

tests run 20-25% faster with not-parallel run on my machine

Use only in-process CLI tests

---

README.rst
docs/changelog.rst
src/schemathesis/__init__.py
src/schemathesis/cli/__init__.py
src/schemathesis/runner/__init__.py
test/cli/test_commands.py

Add a way to register custom checks for CLI

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/app/__init__.py
test/test_runner.py

Fix #272 
Hej @Ricordel !
I fixed the issue you reported, hopefully, we will make a new release soon

Quote path parameters to avoid wrong requests

---

README.rst
test/app/__init__.py
test/app/handlers.py
test/cli/test_commands.py
test/conftest.py

Gives ~30% speed improvement on my local machine without xdist

Make app fixture session scope to speedup tests

---

docs/changelog.rst
src/schemathesis/extra/pytest_plugin.py
test/test_parametrization.py
test/test_pytest.py

Fix support for tests defined as methods

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/models.py
src/schemathesis/schemas.py
test/test_direct_access.py
test/test_hypothesis.py
test/test_models.py
test/test_petstore.py

Refactor case generation strategies

---

docs/changelog.rst
src/schemathesis/models.py
test/app/__init__.py
test/test_runner.py

Improve error message for invalid path parameter declaration.

---

docs/changelog.rst
src/schemathesis/cli/output.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/events.py
test/cli/test_commands.py

feat(cli): Handling of `KeyboardInterrupt` during the CLI run

---

docs/changelog.rst
src/schemathesis/schemas.py
test/app/__init__.py
test/cli/test_commands.py
test/test_schemas.py

Refs #294
The approach depends on the current working directory, but it seems to be fine

feat(schemas): Resolving references that point to different files

---

docs/changelog.rst
src/schemathesis/schemas.py
test/test_dereferencing.py

feat(schemas): Add support for resolving references in `PathItem` objects

---

docs/changelog.rst
src/schemathesis/loaders.py
src/schemathesis/schemas.py
test/test_dereferencing.py

Fix resolving of relative paths in schemas

---

docs/changelog.rst
src/schemathesis/loaders.py
src/schemathesis/schemas.py
src/schemathesis/utils.py
test/test_parameters.py
test/utils.py

Fix loading string dates as `datetime.date` objects in YAML loader

---

src/schemathesis/cli/__init__.py
src/schemathesis/cli/output/__init__.py
src/schemathesis/cli/output/default.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/checks.py
test/cli/output/test_default.py
test/runner/test_checks.py
test/runner/test_runner.py

The main goal is to prepare our codebase for parallel tests execution via runner

Refactoring

---

.github/workflows/release.yml

ci: Fix typo in release workflow

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
test/cli/test_commands.py

Fix `base-url` CLI parameter validation

---

docs/changelog.rst
src/schemathesis/models.py

Closes #322 
It is compatible with the previous Hypothesis versions

Fix compatibility with Hypothesis >= 4.53.2

---

src/schemathesis/loaders.py
src/schemathesis/models.py
src/schemathesis/runner/checks.py
src/schemathesis/utils.py
test/app/__init__.py
test/app/handlers.py
test/cli/test_callbacks.py
test/conftest.py
test/data/simple_swagger.yaml

Backported from #283 to decrease the PR size

Small fixes

---

src/schemathesis/cli/callbacks.py

__import__ behavior seems to be environment-dependent. I don't completely understand the root cause yet, but on my Mac machine `__import__` returns a parent module and on Linux, it is the module I wanted to import :/
`__import__("test.apps._flask.app")` - `test/__init__.py` on Mac and `test/apps/_flask/app.py` on Linux

fix: Importing WSGI applications

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/scheduled.yml
README.rst
docs/changelog.rst
pyproject.toml
src/schemathesis/_hypothesis.py
src/schemathesis/checks.py
src/schemathesis/cli/__init__.py
src/schemathesis/cli/output/default.py
src/schemathesis/models.py
src/schemathesis/runner/__init__.py
src/schemathesis/schemas.py
test/apps/_flask/__init__.py
test/cli/output/test_default.py
test/cli/test_commands.py
test/runner/test_checks.py
test/runner/test_runner.py
test/test_dereferencing.py
test/test_direct_access.py
test/test_hypothesis.py
test/test_models.py
test/test_wsgi.py

Add `Case.verify_response` for running built-in checks against app's response

---

docs/changelog.rst
src/schemathesis/checks.py
test/runner/test_checks.py

feat: Add support for response code ranges

---

docs/changelog.rst
src/schemathesis/checks.py
src/schemathesis/schemas.py
test/runner/test_checks.py

Response schema conformance check for Open API 3.0

---

docs/changelog.rst
src/schemathesis/schemas.py
test/test_dereferencing.py

Fix handling `nullable` attribute in Open API schemas

---

README.rst
docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/extra/_aiohttp.py
src/schemathesis/loaders.py
test/apps/_aiohttp/__init__.py
test/apps/_aiohttp/app.py
test/cli/test_commands.py
test/conftest.py
test/extra/test_aiohttp.py

WIP: Support for AioHTTP applications in CLI

---

.github/workflows/build.yml
test/cli/test_commands.py
tox.ini

Add tests for different Hypothesis versions

---

docs/changelog.rst
src/schemathesis/checks.py
src/schemathesis/exceptions.py
test/runner/test_checks.py

Raise different exceptions in checks

---

pyproject.toml
test/cli/test_commands.py
tox.ini

Fix builds for Hypothesis 5.0+

---

docs/changelog.rst
src/schemathesis/models.py
test/apps/_aiohttp/handlers.py
test/apps/_flask/__init__.py
test/apps/utils.py
test/cli/test_commands.py
test/test_petstore.py
test/test_wsgi.py
test/utils.py

Handling binary request payloads in ``Case.call``

---

docs/changelog.rst
src/schemathesis/schemas.py
test/test_schemas.py

Raise proper exception when the given schema is invalid

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/exceptions.py
src/schemathesis/runner/__init__.py
src/schemathesis/utils.py
test/apps/_aiohttp/handlers.py
test/apps/_flask/__init__.py
test/apps/utils.py
test/cli/output/test_default.py
test/cli/test_commands.py

WIP: Display multiple found failures in CLI

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/options.py
test/cli/test_commands.py

Support for `None` as a value for `--hypothesis-deadline`

---

README.rst
docs/changelog.rst
src/schemathesis/__init__.py
src/schemathesis/_hypothesis.py
src/schemathesis/constants.py
src/schemathesis/hooks.py
src/schemathesis/schemas.py
src/schemathesis/types.py
test/test_hooks.py

Hooks for strategy modification

---

.dockerignore
.github/workflows/release.yml
.github/workflows/scheduled.yml
Dockerfile
pyproject.toml

Remove the poetry environment from the docker image

---

README.rst
docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/loaders.py
src/schemathesis/spec_schemas.py
test/cli/test_commands.py
test/conftest.py
test/test_lazy.py
test/test_parameters.py
test/test_parametrization.py
test/test_schemas.py

Validate input schemas with `jsonschema`

---

src/schemathesis/checks.py
test/runner/test_checks.py

Prevent KeyError when response does not have Content-Type

---

docs/changelog.rst
src/schemathesis/converter.py
src/schemathesis/schemas.py
test/cli/test_callbacks.py
test/test_converter.py

Fix converting Open API parameters to JSON Schema

---

src/schemathesis/cli/__init__.py
test/cli/test_commands.py
tox.ini

Add 'all' options for running checks in CLI

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/runner/__init__.py
test/cli/test_commands.py
test/runner/test_runner.py

CLI option to fail after the first error

---

test/runner/test_runner.py

It is not relevant to the test's scope

fix(tests): Exclude special case from test_path_parameters_encoding

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/loaders.py
src/schemathesis/schemas.py
test/test_hypothesis.py

feat: Allow bodies for GET requests if schema validation is disabled

---

docs/changelog.rst
src/schemathesis/schemas.py
test/test_parametrization.py

feat: Support for testing of examples in Parameter & Media Type objects in Open API 3.0.

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
src/schemathesis/utils.py
test/cli/test_callbacks.py
test/cli/test_commands.py
test/cli/test_crashes.py

Fixes #403 
Fixes #404 
Fixes #405 
Fixes #406
Fixes #407

Improve input validation

---

docs/changelog.rst
src/schemathesis/schemas.py
test/conftest.py
test/test_parametrization.py

Fix not copied `validate_schema` parameter in `BaseSchema.parametrize`

---

docs/changelog.rst
src/schemathesis/lazy.py
src/schemathesis/schemas.py
test/test_hooks.py
test/test_wsgi.py

Fix not passed attributes

---

.github/workflows/build.yml
test/cli/output/test_default.py
test/cli/test_commands.py
test/cli/test_crashes.py
test/generation/test_complex.py
test/test_app.py
test/test_dereferencing.py
test/test_parameters.py
test/test_petstore.py
test/utils.py

chore(ci): Add Windows build

---

.github/workflows/scheduled.yml

chore(ci): Fix mutmut job

---

.github/workflows/scheduled.yml
test/conftest.py
test/test_hooks.py
test/test_hypothesis.py
test/test_parameters.py
test/test_wsgi.py

chore(ci): Run scheduled hypothesis tests with custom profile

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/test_hypothesis.py
test/test_parametrization.py

chore: Change handling of explicit examples from schemas

---

test/cli/test_commands.py
test/runner/test_runner.py

chore(tests): Add tests for loader options

---

docs/changelog.rst
src/schemathesis/schemas.py

Hi, 
this is the fix i mentioned in #435 
I limited the recursion limit to a depth of 100 which should be enough.

Fix: dont break on recursive json schemas

---

docs/changelog.rst
src/schemathesis/schemas.py
test/test_parametrization.py

fix: Handling of schemas, that use `x-*` custom properties

---

docs/changelog.rst
src/schemathesis/checks.py
src/schemathesis/models.py
src/schemathesis/schemas.py
test/runner/test_checks.py

fix: Content Type conformance check for Open API 3.0 schemas

---

docs/changelog.rst
src/schemathesis/schemas.py
test/runner/test_checks.py

fix: Error in `OpenApi30.get_content_types` introduced in `8aeee1a`

---

docs/changelog.rst
src/schemathesis/checks.py
test/apps/_aiohttp/handlers.py
test/apps/_flask/__init__.py
test/apps/utils.py
test/runner/test_runner.py

fix: Response schema check for recursive schemas

---

docs/changelog.rst
src/schemathesis/checks.py
src/schemathesis/converter.py
src/schemathesis/schemas.py
test/apps/utils.py
test/test_converter.py

Fix OpenAPI -> JSON Schema conversion

---

docs/changelog.rst
src/schemathesis/loaders.py
src/schemathesis/runner/__init__.py
test/runner/test_runner.py

Runner custom loaders

---

README.rst
docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/models.py
src/schemathesis/schemas.py
test/test_hooks.py

feat: Per-test hooks for modification of data generation strategies

---

docs/changelog.rst
src/schemathesis/schemas.py
test/test_parametrization.py

feat: Support `x-example` vendor extension in Open API 2.0

---

docs/changelog.rst
src/schemathesis/runner/__init__.py
test/runner/test_runner.py

chore: Sanity validation for `runner.prepare` parameters

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
test/cli/output/test_default.py
test/cli/test_commands.py

It will be helpful to have different subsections there (the next one will be for logs)

chore: Add indentation & section name to the `SUMMARY` CLI block.

---

src/schemathesis/cli/__init__.py
src/schemathesis/cli/cassettes.py
src/schemathesis/cli/handlers.py
test/cli/test_cassettes.py

No changelog entry since it is a fix to the feature that is not released yet

chore: Shutdown writer thread in case of exceptions in the main thread

---

docs/changelog.rst
poetry.lock
pyproject.toml

chore:  Update `pytest-subtests` pin to `>=0.2.1,<1.0`

---

docs/changelog.rst
docs/compatibility.rst
docs/faq.rst
docs/index.rst
src/schemathesis/__init__.py
src/schemathesis/cli/__init__.py
src/schemathesis/converter.py
src/schemathesis/fixups/__init__.py
src/schemathesis/fixups/fast_api.py
src/schemathesis/hooks.py
src/schemathesis/loaders.py
src/schemathesis/runner/__init__.py
src/schemathesis/utils.py
test/cli/test_commands.py
test/conftest.py
test/test_fixups.py

feat: Third-party compatibility fixups mechanism

---

docs/changelog.rst
src/schemathesis/checks.py
src/schemathesis/converter.py
src/schemathesis/models.py
src/schemathesis/schemas.py
test/conftest.py
test/runner/test_checks.py
test/test_converter.py
test/test_dereferencing.py

fix: Reference resolving during response schema conformance check

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/runner/events.py
test/cli/test_commands.py

feat: Display suggestion to disable schema validation if it happens in CLI

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/impl/solo.py
src/schemathesis/runner/impl/threadpool.py
test/apps/_aiohttp/handlers.py
test/apps/_flask/__init__.py
test/apps/utils.py
test/runner/test_runner.py

fix: Overriding headers in CLI & runner

---

docs/changelog.rst
src/schemathesis/checks.py
src/schemathesis/converter.py
src/schemathesis/models.py
src/schemathesis/schemas.py
test/conftest.py
test/runner/test_checks.py

fix: Nested references resolving in `response_schema_conformance` check

---

docs/changelog.rst
docs/customization.rst
src/schemathesis/_hypothesis.py
src/schemathesis/hooks.py
test/conftest.py
test/hooks/test_hooks.py

feat: New `before_add_examples` hook

---

docs/changelog.rst
docs/customization.rst
src/schemathesis/cli/__init__.py
test/cli/test_hooks.py

feat: New `after_init_cli_run_handlers` hook

---

test/cli/test_cassettes.py
test/cli/test_commands.py
test/cli/test_hooks.py
test/cli/test_junitxml.py

It will help with debugging of flaky tests on CI

test: Display stdout when tests are failing

---

docs/changelog.rst
src/schemathesis/specs/openapi/schemas.py
src/schemathesis/specs/openapi/serialization.py
test/specs/openapi/test_serializing.py

feat: Support serializing parameters with `application/json` content type

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/specs/openapi/schemas.py
test/runner/test_checks.py
test/test_dereferencing.py
test/test_direct_access.py
test/test_hypothesis.py

fix: `KeyError` during creating endpoint strategy if it contains a reference

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/context.py
src/schemathesis/cli/output/default.py
test/cli/output/test_default.py
test/cli/test_commands.py

Resolves #598 
Github didn't allow to force push to the fork (or I messed up with my git command). This is a replacement for #609 based on the original commit with my cleanups. Also, since this is the main repo branch, codecov should be able to report & upload coverage correctly.
cc @presto21

feat: add CLI option to minimize the verbose schema error

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/test_hypothesis.py

fix: Crash during generation of loosely-defined headers

---

docs/changelog.rst
src/schemathesis/lazy.py
src/schemathesis/schemas.py
test/test_lazy.py

feat: Support for hook usage via `LazySchema` / from_pytest_fixture`

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/cli/output/default.py
src/schemathesis/hooks.py
src/schemathesis/runner/events.py

Forgot to remove it in before 2.0 :(

Remove deprecated code

---

test/cli/test_cassettes.py

Query parameters are escaped during serialization

test: Fix flaky test

---

docs/changelog.rst
src/schemathesis/specs/openapi/serialization.py
test/specs/openapi/test_serializing.py

fix: Serialization of non-string parameters

---

docs/changelog.rst
docs/graphql.rst
src/schemathesis/__init__.py
src/schemathesis/_hypothesis.py
src/schemathesis/specs/graphql/__init__.py
src/schemathesis/specs/graphql/loaders.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/examples.py

Various changes & improvements for GraphQL schemas testing

---

pytest.ini

chore: Add `norecursedirs` config option for pytest to reduce the time for tests collection

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/test_parametrization.py

fix: `AttributeError` during generation of "multipart/form-data" parameters that have no "type" defined

---

docs/changelog.rst
src/schemathesis/specs/openapi/references.py
test/test_parametrization.py

fix: Support for properties named "$ref" in object schemas

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/test_hypothesis.py

fix: Generating illegal unicode surrogates in path

---

docs/changelog.rst
poetry.lock
pyproject.toml
test/apps/__init__.py
tox.ini

Fix scheduled builds

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
test/cli/test_cassettes.py

fix: Encoding error when writing a cassette on Windows

---

docs/changelog.rst
docs/targeted.rst
src/schemathesis/__init__.py
src/schemathesis/cli/__init__.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/impl/threadpool.py
src/schemathesis/runner/targeted.py
src/schemathesis/targets.py
test/cli/test_commands.py
test/cli/test_targeted.py

feat: Customizable targets for targeted testing

---

docs/changelog.rst
src/schemathesis/checks.py
src/schemathesis/cli/__init__.py
src/schemathesis/exceptions.py
src/schemathesis/models.py
test/cli/test_checks.py
test/cli/test_targeted.py

Return from `register`

---

test/test_asgi.py
test/test_wsgi.py

They might be slow in some cases, but it should not make the CI fail

test: Disable deadline on some Hypothesis tests

---

src/schemathesis/_hypothesis.py
src/schemathesis/models.py
src/schemathesis/schemas.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/constants.py
src/schemathesis/specs/openapi/examples.py
src/schemathesis/specs/openapi/links.py
src/schemathesis/specs/openapi/schemas.py
test/test_hypothesis.py

Preparation for a better GraphQL integration

refactor: Make `get_case_strategy` dependent on the used spec

---

docs/changelog.rst
docs/stateful.rst
src/schemathesis/__init__.py
src/schemathesis/_hypothesis.py
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
src/schemathesis/constants.py
src/schemathesis/extra/pytest_plugin.py
src/schemathesis/models.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/impl/__init__.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/impl/threadpool.py
src/schemathesis/schemas.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/schemas.py
src/schemathesis/stateful.py
test/conftest.py
test/specs/openapi/test_links.py
test/test_stateful.py

Working prototype
Resolves #616 
TODO:

feat: Stateful testing for the `pytest` runner

---

docs/changelog.rst
docs/graphql.rst
src/schemathesis/specs/graphql/schemas.py
test/specs/graphql/test_basic.py
test/specs/graphql/test_pytest.py

feat: Support for GraphQL schemas for the `pytest` runner

---

docs/changelog.rst
src/schemathesis/models.py

Create shortcut for calling and validation.

feat: Shortcut for calling & validation

---

README.rst

The FlaskCon video only got audio on the right channel, and the content was improved with help of @Stranger6667 for the EuroPython version.

docs: Replaced video from FlaskCon with EuroPython

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/specs/graphql/schemas.py
test/cli/test_cassettes.py
test/runner/test_runner.py

Set default User-Agent header in Case.call.

fix: Set default User-Agent header in Case.call

---

docs/changelog.rst
src/schemathesis/loaders.py
src/schemathesis/models.py
src/schemathesis/runner/impl/core.py
test/test_models.py

Fix User-Agent header overriding the passed one.

fix: fix User-Agent header overriding the passed one

---

test/cli/test_cassettes.py

Path should be properly quoted as well. Sometimes this test fails on CI

test: Fix flaky `test_replay` test

---

docs/changelog.rst
src/schemathesis/cli/cassettes.py

fix: Escaping HTTP response message in VCR cassettes

---

.github/workflows/build.yml
docs/changelog.rst
pyproject.toml
tox.ini

ci: Add python 3.9 builds

---

docs/changelog.rst
docs/cli.rst
docs/python.rst
src/schemathesis/checks.py
src/schemathesis/exceptions.py
src/schemathesis/specs/openapi/checks.py
src/schemathesis/specs/openapi/schemas.py
test/apps/_aiohttp/handlers.py
test/apps/_flask/__init__.py
test/apps/utils.py
test/cli/test_commands.py

feat: New `response_headers_conformance` check that verifies the presence of all headers defined for a response

---

docs/changelog.rst
src/schemathesis/models.py
test/test_models.py
test/test_pytest.py

feat: A code snippet to reproduce a failed check when running Python tests

---

docs/changelog.rst
docs/cli.rst
docs/python.rst
src/schemathesis/cli/__init__.py
src/schemathesis/lazy.py
src/schemathesis/loaders.py
src/schemathesis/runner/__init__.py
src/schemathesis/schemas.py
src/schemathesis/specs/openapi/filters.py
src/schemathesis/specs/openapi/schemas.py
test/cli/test_commands.py
test/test_parametrization.py

feat: Ability to skip deprecated endpoints

---

src/schemathesis/models.py
src/schemathesis/specs/openapi/links.py
src/schemathesis/stateful.py
test/apps/utils.py

E.g., when using verbose hypothesis output, it will reduce the noise

chore: Improve repr output

---

docs/changelog.rst
poetry.lock
pyproject.toml
src/schemathesis/models.py
test/test_case_curl_cmd.py

Closes #689 
Add a method `as_curl_command` to the Case class to generate a string with the curl command for manual testing

feat: generate cURL from Case instance

---

test/cli/test_callbacks.py

To avoid failing builds like this one - https://github.com/schemathesis/schemathesis/pull/805/checks?check_run_id=1276472630

test: Do not generate known to be valid values for `test_validate_header`

---

docs/changelog.rst
src/schemathesis/exceptions.py
src/schemathesis/specs/openapi/checks.py
test/runner/test_checks.py

chore: Content-Type header is required for `response_schema_conformance` and `content_type_conformance` checks

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/utils.py
test/specs/openapi/test_stateful.py
test/test_pytest.py

fix: Failure reproduction code missing actually executed values

---

docs/changelog.rst
src/schemathesis/specs/openapi/schemas.py
test/test_stateful.py

fix: Adding new Open API links via the ``add_link`` method, when the related PathItem contains a reference

---

docs/changelog.rst
src/schemathesis/cli/callbacks.py
src/schemathesis/utils.py
test/cli/test_commands.py
test/test_utils.py

chore: Improve the error message when the application can not be loaded from the value passed to the `--app` command-line option

---

docs/changelog.rst
src/schemathesis/specs/openapi/serialization.py
test/test_parameters.py

fix: Internal error when a "header" / "cookie" parameter were not coerced to a string before filtration

---

docs/changelog.rst
src/schemathesis/specs/openapi/schemas.py
src/schemathesis/specs/openapi/security.py
test/test_parameters.py

chore: Serialize security definitions

---

docs/cli.rst

Fix for https://github.com/schemathesis/schemathesis/issues/845
No new behavior added. No new tests or changelogs a required.

fix: Fix typo in CLI docs.

---

docs/changelog.rst
src/schemathesis/exceptions.py
src/schemathesis/specs/openapi/schemas.py
src/schemathesis/utils.py
test/cli/test_junitxml.py
test/runner/test_runner.py

fix: Internal error on malformed JSON when the `response_conformance` check is used

---

docs/changelog.rst
src/schemathesis/models.py
test/test_models.py

fix: Code samples for error reproduction

---

docs/changelog.rst
poetry.lock
pyproject.toml

fix: Relax `attrs` dependency

---

docs/changelog.rst
src/schemathesis/cli/output/default.py

chore: Extend CLI message on invalid endpoint schemas

---

docs/changelog.rst
src/schemathesis/cli/callbacks.py
test/cli/test_callbacks.py

fix: Internal error in CLI, when the schema location is an invalid IPv6

---

docs/changelog.rst
src/schemathesis/specs/openapi/links.py
test/apps/utils.py

fix: Collecting Open API links behind references via CLI

---

docs/cli.rst

* Explain the format of the `--auth` argument
* Explain how to use a spec from disk

Documentation additions for the cli

---

docs/changelog.rst
src/schemathesis/cli/callbacks.py
test/cli/test_callbacks.py
test/cli/test_crashes.py

Fix internal errors

---

test/cli/test_commands.py

test: Stabilize tests that cover handling of keyboard interruption

---

docs/changelog.rst
src/schemathesis/models.py
test/test_models.py

chore: Improve "Falsifying example" section readability

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/specs/openapi/schemas.py
src/schemathesis/utils.py
test/test_models.py

feat: Display failed response payload in the error output

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/serializers.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/stateful.py
test/apps/_aiohttp/handlers.py
test/cli/output/test_default.py
test/conftest.py
test/test_async.py
test/test_hypothesis.py
test/test_parameters.py
test/test_petstore.py
test/test_stateful.py

fix: Allow sending ``null`` as request payload if the schema expects it

---

docs/changelog.rst
src/schemathesis/specs/openapi/schemas.py
test/runner/test_checks.py

feat: Run `response_schema_conformance` check on media types that are encoded with JSON

---

src/schemathesis/models.py
src/schemathesis/serializers.py
src/schemathesis/specs/openapi/serialization.py
test/apps/utils.py
test/cli/test_commands.py
test/test_hypothesis.py
test/test_models.py
test/test_parametrization.py
test/test_stateful.py

Add more tests

---

src/schemathesis/specs/graphql/schemas.py

refactor: Remove not needed code for GraphQL schemas

---

src/schemathesis/models.py

Form data can't be `None` at this point

refactor: Remove not needed condition

---

CONTRIBUTING.rst
docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/specs/openapi/_hypothesis.py
test/apps/__init__.py
test/apps/_aiohttp/handlers.py
test/apps/utils.py
test/runner/test_runner.py

chore: Enforce path parameters to be required if schema validation is disabled

---

docs/changelog.rst
src/schemathesis/specs/graphql/loaders.py
src/schemathesis/specs/graphql/schemas.py
test/specs/graphql/test_basic.py

feat: Base URL for GraphQL schemas

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
test/cli/test_commands.py

chore: Disallow using `--auth` together with `--header` that sets the `Authorization` header.

---

poetry.lock
pyproject.toml

fix: Add missing dependency on `typing_extension`

---

docs/changelog.rst
src/schemathesis/serializers.py
src/schemathesis/utils.py
test/apps/_aiohttp/handlers.py
test/apps/_flask/__init__.py
test/runner/test_runner.py
test/test_utils.py

feat: Support data generation for `text/plain` media types with `charset`

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/context.py
src/schemathesis/cli/output/default.py
test/cli/test_commands.py

fix: Do not suggest to disable schema validation if it is already disabled

---

docs/changelog.rst
src/schemathesis/schemas.py
test/test_models.py

feat: A helpful error message when an operation is not found during the direct schema access

---

src/schemathesis/cli/__init__.py
src/schemathesis/cli/output/default.py
test/cli/output/test_default.py

refactor: Move exit code decision out from the output handler

---

docs/changelog.rst
src/schemathesis/specs/openapi/stateful/__init__.py
test/apps/_aiohttp/__init__.py
test/apps/_aiohttp/handlers.py
test/apps/_fastapi/__init__.py
test/apps/_flask/__init__.py
test/apps/utils.py
test/specs/openapi/test_links.py
test/specs/openapi/test_stateful.py

Fix "Unsatisfiable" error in stateful testing

---

docs/changelog.rst
src/schemathesis/specs/openapi/stateful/__init__.py
src/schemathesis/stateful.py
test/specs/openapi/test_stateful.py

fix: A possibility to override `APIStateMachine.step`

---

docs/changelog.rst
src/schemathesis/exceptions.py
src/schemathesis/models.py
src/schemathesis/runner/impl/core.py
test/runner/test_runner.py

chore: Display all non-check failures in CLI tests

---

src/schemathesis/specs/openapi/examples.py
test/specs/openapi/test_examples.py

Regression after parameters refactoring

fix: Explicit examples for multipart forms

---

docs/changelog.rst
src/schemathesis/specs/openapi/serialization.py
test/specs/openapi/test_serializing.py

Fixes #980
TODO:
- Verify how nullable options will look like

fix: `TypeError` during nullable `array` parameter serialization

---

docs/changelog.rst
src/schemathesis/specs/openapi/_hypothesis.py
test/cli/test_commands.py

fix: CLI execution stops on errors during example generation

---

docs/changelog.rst
src/schemathesis/parameters.py
src/schemathesis/specs/openapi/references.py
src/schemathesis/specs/openapi/schemas.py
src/schemathesis/utils.py

perf: Improve processing of API operation definitions

---

.github/workflows/build.yml
docs/requirements.txt

ci: Add a CI job to check docs

---

docs/changelog.rst
poetry.lock
pyproject.toml
src/schemathesis/exceptions.py
src/schemathesis/runner/impl/core.py
test/cli/test_commands.py
test/specs/openapi/test_stateful.py

chore: A better error message for invalid regex syntax

---

docs/changelog.rst
src/schemathesis/specs/openapi/_hypothesis.py
test/specs/openapi/test_examples.py
test/specs/openapi/test_hypothesis.py

fix: Generating incomplete explicit examples

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/exceptions.py
src/schemathesis/extra/pytest_plugin.py
src/schemathesis/lazy.py
src/schemathesis/models.py
src/schemathesis/runner/events.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/impl/threadpool.py
src/schemathesis/runner/serialization.py
src/schemathesis/schemas.py
src/schemathesis/specs/graphql/schemas.py
src/schemathesis/specs/openapi/schemas.py
src/schemathesis/specs/openapi/stateful/__init__.py
src/schemathesis/stateful.py
src/schemathesis/utils.py
test/conftest.py
test/specs/openapi/test_examples.py
test/test_examples.py
test/test_loaders.py
test/test_recoverable_errors.py
test/test_schemas.py

chore: Continue testing after schema parsing errors if possible

---

docs/changelog.rst
src/schemathesis/serializers.py
test/conftest.py
test/test_serialization.py

feat: Support YAML serialization

---

docs/changelog.rst
src/schemathesis/specs/openapi/_hypothesis.py

Fixes #1018
I didn't manage to write a proper regression test yet, verified only on the test corpus test linked in the issue

fix: `Flaky` Hypothesis error during explicit examples generation

---

docs/changelog.rst
src/schemathesis/serializers.py
src/schemathesis/specs/openapi/examples.py
test/apps/_aiohttp/__init__.py
test/specs/openapi/test_examples.py

feat: Support for external examples

---

docs/changelog.rst
poetry.lock
pyproject.toml

fix: loosen importlib-metadata version constraint

---

docs/changelog.rst
poetry.lock
pyproject.toml
src/schemathesis/lazy.py
src/schemathesis/runner/impl/core.py
test/runner/test_runner.py
test/specs/openapi/test_stateful.py
test/test_async.py

The health check should fail on the "lazy" workflow in all cases, but it fails only if a test is wrapped with `settings`. Need to check deeper

chore: Support Hypothesis 6

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/models.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/serialization.py
test/cli/output/test_default.py
test/cli/test_commands.py

feat: Display failing response payload in the CLI output

---

docs/changelog.rst
src/schemathesis/runner/events.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/serialization.py
test/cli/output/test_default.py

chore: Add extra information to events, emitted by the Schemathesis runner

---

docs/changelog.rst
docs/cli.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
src/schemathesis/cli/context.py
src/schemathesis/cli/output/default.py
src/schemathesis/constants.py
src/schemathesis/lazy.py
src/schemathesis/loaders.py
src/schemathesis/models.py
src/schemathesis/runner/serialization.py
src/schemathesis/schemas.py
src/schemathesis/specs/graphql/schemas.py
test/cli/test_commands.py
test/test_curl.py
test/test_lazy.py
test/test_loaders.py
test/test_pytest.py
test/test_schemas.py

Control code sample style

---

docs/changelog.rst
docs/cli.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/debug.py
src/schemathesis/models.py
src/schemathesis/runner/events.py
test/cli/test_commands.py

feat: `--debug-output-file` CLI option

---

docs/changelog.rst
docs/extending.rst
src/schemathesis/hooks.py
src/schemathesis/models.py
src/schemathesis/specs/openapi/_hypothesis.py
test/hooks/test_hooks.py

It allows the user to modify or filter generated `Case` instances
Resolves #1067

feat: `before_generate_case` hook

---

CONTRIBUTING.rst
docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/models.py
test/apps/_aiohttp/handlers.py
test/apps/_flask/__init__.py
test/apps/utils.py
test/cli/test_commands.py

fix: Encoding for response payloads displayed in the CLI output

---

docs/changelog.rst
src/schemathesis/exceptions.py
src/schemathesis/loaders.py
src/schemathesis/specs/graphql/__init__.py
src/schemathesis/specs/graphql/loaders.py
src/schemathesis/specs/graphql/schemas.py
test/specs/graphql/test_pytest.py

feat: `from_wsgi` loader for GraphQL apps

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/impl/core.py
test/cli/test_commands.py

Few more steps towards GraphQL support there

Refactor Schemathesis runner

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/exceptions.py
src/schemathesis/runner/impl/core.py
test/cli/test_commands.py

chore: Improve error message for failing Hypothesis deadline healthcheck in CLI

---

docs/changelog.rst
poetry.lock
pyproject.toml

chore: Relax dependency on `starlette` to `>=0.13,<1`

---

docs/changelog.rst
src/schemathesis/specs/openapi/parameters.py
src/schemathesis/specs/openapi/schemas.py
test/specs/openapi/test_hypothesis.py

Fix schemas transformation

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/constants.py
src/schemathesis/exceptions.py
src/schemathesis/failures.py
src/schemathesis/models.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/serialization.py
test/cli/test_commands.py
test/test_parametrization.py
test/test_pytest.py

chore: Set default timeout for network requests to 10 seconds.

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/serializers.py
test/specs/openapi/test_serializing.py

fix: Internal error on unusual schemas for the `multipart/form-data` media type

---

docs/changelog.rst
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/utils.py
test/specs/openapi/test_hypothesis.py

fix: Too much filtering in headers that have schemas with the `pattern` keyword

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/output/default.py
src/schemathesis/exceptions.py
src/schemathesis/models.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/serialization.py
src/schemathesis/specs/graphql/loaders.py
test/cli/output/test_default.py
test/cli/test_commands.py
test/conftest.py

Resolves #746
Works locally against the test app.
TODO:

feat: GraphQL support in CLI

---

docs/changelog.rst
src/schemathesis/specs/openapi/serialization.py
test/specs/openapi/test_negative.py

fix: `TypeError` during negative testing on Open API schemas with parameters that have non-default `style` value

---

docs/changelog.rst
docs/extending.rst
src/schemathesis/cli/__init__.py
src/schemathesis/runner/impl/core.py
test/cli/conftest.py
test/cli/test_commands.py
test/cli/test_hooks.py

feat: New `before_call` and `after_call` CLI hooks.

---

docs/changelog.rst
docs/extending.rst
src/schemathesis/cli/__init__.py
src/schemathesis/runner/impl/core.py
test/cli/test_hooks.py

feat: New `process_call_kwargs` CLI hook

---

docs/changelog.rst
src/schemathesis/runner/impl/threadpool.py

fix: Stop workers on interrupted event

---

poetry.lock
pyproject.toml

Relaxed `colorama` and `typing-extension`. Got hit by it today.
Closes #1258 
None of those things 😢

Relax colorama and typing-extensions

---

docs/changelog.rst
src/schemathesis/exceptions.py
src/schemathesis/specs/openapi/loaders.py
test/loaders/test_openapi.py

chore: Improve error messages when the loaded API schema is not in JSON or YAML

---

.github/workflows/build.yml
.github/workflows/scheduled.yml

Newer poetry version fails on Windows

build: Use poetry<1.1.9

---

docs/changelog.rst
poetry.lock
pyproject.toml

fix: Unresolvable dependency due to incompatible changes in the new `hypothesis-jsonschema` release

---

docs/changelog.rst
src/schemathesis/runner/impl/threadpool.py

perf: Generate tests on demand when multiple workers are used during CLI runs

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/specs/graphql/schemas.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/schemas.py
test/specs/openapi/test_serializing.py
test/test_models.py

chore: Use case-insensitive dictionary for `Case.headers`

---

CONTRIBUTING.rst
docs/changelog.rst
src/schemathesis/specs/openapi/converter.py
src/schemathesis/specs/openapi/references.py
src/schemathesis/specs/openapi/schemas.py
test/apps/openapi/_aiohttp/handlers.py
test/apps/openapi/_flask/__init__.py
test/apps/openapi/schema.py
test/test_converter.py
test/test_parameters.py

feat: Support for `readOnly` and `writeOnly` Open API keywords

---

poetry.lock
pyproject.toml
test/test_parametrization.py

To avoid git dependency -> upgrade poetry -> run Python 3.10 builds

chore: Update dev dependencies

---

.github/workflows/build.yml
docs/changelog.rst
pyproject.toml
test/cli/output/test_default.py
tox.ini

Python 3.10 support

---

docs/changelog.rst
src/schemathesis/models.py
test/code_samples/test_python.py

fix: Not-escaped single quotes in generated Python code samples

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/cassettes.py
test/cli/test_cassettes.py

feat: Extra `requests` related options for the `replay` command

---

.pre-commit-config.yaml
docs/changelog.rst
pyproject.toml
src/schemathesis/_compat.py
src/schemathesis/utils.py

Addresses the recent incompatibility between Black & Click

chore: Update pre-commit

---

docs/changelog.rst
src/schemathesis/models.py
test/runner/test_runner.py

chore: Improve error message on malformed Open API path templates

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
src/schemathesis/cli/options.py
test/apps/__init__.py
test/cli/test_commands.py
test/cli/test_options.py

feat: Support for comma separated lists in the `--checks` CLI option

---

docs/changelog.rst
src/schemathesis/specs/openapi/checks.py
src/schemathesis/utils.py
test/runner/test_checks.py
test/test_utils.py

chore: Improve error messages for malformed media types

---

.rstcheck.cfg
docs/api.rst
docs/auth.rst
docs/changelog.rst
docs/cli.rst
docs/index.rst
docs/recipes.rst
poetry.lock
src/schemathesis/__init__.py
src/schemathesis/_hypothesis.py
src/schemathesis/auth.py
src/schemathesis/models.py
src/schemathesis/runner/impl/core.py
src/schemathesis/schemas.py
src/schemathesis/specs/graphql/schemas.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/schemas.py
test/auth/conftest.py
test/auth/test_cli.py
test/auth/test_provider.py
test/auth/test_pytest.py
test/service/test_cli.py

feat: Support for auth customization & automatic refreshing

---

poetry.lock
test/conftest.py
test/test_lazy.py
test/test_recoverable_errors.py

test: Support multiple `pytest-subtests` versions in tests

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/constants.py
src/schemathesis/exceptions.py
src/schemathesis/extra/pytest_plugin.py
src/schemathesis/lazy.py
src/schemathesis/models.py
src/schemathesis/runner/events.py
src/schemathesis/runner/impl/core.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/negative/mutations.py
src/schemathesis/specs/openapi/negative/utils.py
test/cli/test_commands.py
test/conftest.py
test/test_lazy.py
test/test_pytest.py

chore: Skip negative tests on API operations that are not possible to negate

---

docs/changelog.rst
src/schemathesis/lazy.py
test/conftest.py
test/test_lazy.py

I remember it was reported somewhere, but can't find it :(

fix: `schemathesis.from_pytest_fixture`: Display each failure if Hypothesis found multiple of them

---

docs/changelog.rst
src/schemathesis/utils.py
test/cli/test_commands.py

chore: Do not duplicate failing explicit example in the `HYPOTHESIS OUTPUT` CLI output section

---

docs/changelog.rst
src/schemathesis/failures.py
test/apps/openapi/_aiohttp/handlers.py
test/apps/openapi/_flask/__init__.py
test/cli/test_commands.py

fix: Deduplication of failures caused by malformed JSON payload

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/runner/impl/core.py
test/cli/test_commands.py

chore: Mark tests as skipped if there are no explicit examples and `--hypothesis-phases=explicit` is used

---

docs/changelog.rst
src/schemathesis/exceptions.py
src/schemathesis/models.py
src/schemathesis/serializers.py
src/schemathesis/specs/openapi/_hypothesis.py
test/test_serialization.py

feat: Support generating data for Open API request payloads with wildcard media types

---

docs/changelog.rst
docs/extending.rst
docs/stateful.rst
src/schemathesis/hooks.py
src/schemathesis/specs/graphql/loaders.py
src/schemathesis/specs/openapi/loaders.py
test/hooks/test_hooks.py

With this hook, it will be possible to add links in CLI

feat: The `after_load_schema` hook

---

docs/changelog.rst
src/schemathesis/_compat.py
src/schemathesis/lazy.py
src/schemathesis/runner/impl/core.py
test/cli/test_commands.py
test/conftest.py
test/test_unittest.py

chore: Support for exception groups in newer `Hypothesis` versions

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
src/schemathesis/cli/output/default.py
src/schemathesis/extra/pytest_plugin.py
src/schemathesis/lazy.py
src/schemathesis/models.py
src/schemathesis/runner/events.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/impl/threadpool.py
src/schemathesis/runner/serialization.py
src/schemathesis/schemas.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/stateful/__init__.py
src/schemathesis/stateful.py
src/schemathesis/utils.py
test/cli/output/test_default.py
test/cli/test_commands.py
test/specs/graphql/test_pytest.py
test/test_async.py
test/test_filters.py
test/test_lazy.py
test/test_parametrization.py
test/test_pytest.py
test/test_recoverable_errors.py

feat: A way to generate negative and positive test cases within the same CLI run via `-D all`

---

poetry.lock
pyproject.toml
test/cli/test_commands.py
test/runner/test_runner.py

Requests current version is `2.28.1` which is in use in our services, this prevents us from updating schemathesis.

chore(schemathesis): bump requests

---

src/schemathesis/cli/__init__.py

Updated the help message that renders in online docs for `--checks` CLI option to describe how to enter multiple values

update --checks help message

---

README.rst

See https://snarky.ca/why-you-should-use-python-m-pip/

Use python -m pip installation method

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/commit.yml
.github/workflows/example-build.yml
.github/workflows/example-no-build.yml
.github/workflows/release.yml
.github/workflows/scheduled.yml
.pre-commit-config.yaml
CODE_OF_CONDUCT.md
example/app/openapi.yaml
example/docker-compose.yml
test-corpus/flaky.json
test-corpus/incompatible_enums.json
test-corpus/incompatible_regex.json
test-corpus/recursive_references.json
test/data/petstore_v2.yaml
test/data/petstore_v3.yaml
test/data/simple_swagger.yaml

Add prettier hook to pre-commit and prettify repo

---

docs/changelog.rst
src/schemathesis/models.py
test/runner/test_runner.py

fix: Appending an extra slash to the `/` path

---

.github/workflows/build.yml
docs/changelog.rst
poetry.lock
pyproject.toml
src/schemathesis/_compat.py
src/schemathesis/parameters.py
src/schemathesis/specs/openapi/parameters.py
src/schemathesis/specs/openapi/validation.py
test/cli/test_commands.py
tox.ini

chore: Python 3.11 support

---

src/schemathesis/models.py
test/code_samples/test_python.py

refactor: Simplify single quotes escaping

---

docs/changelog.rst
src/schemathesis/specs/openapi/stateful/__init__.py
src/schemathesis/specs/openapi/stateful/links.py
test/specs/openapi/test_stateful.py
test/test_common_parameters.py

chore: Only make stateful requests when stateful data is available from another operation

---

docs/changelog.rst
pyproject.toml

It gives up to 30% faster data generation in some workflows

perf: Update `hypothesis-jsonschema` to `0.22.1`

---

changelog.py

Probably we need to eventually move to some better solution for changelog management, but this script is simple enough to help me with releasing new versions.

chore: A script for changelog management

---

docs/changelog.rst
docs/stateful.rst
src/schemathesis/_compat.py
src/schemathesis/stateful.py
test/specs/openapi/test_stateful.py

chore: Make state machines execute at least two steps

---

docs/auth.rst
docs/changelog.rst
src/schemathesis/__init__.py
src/schemathesis/auths.py
src/schemathesis/models.py
test/auth/test_cli.py
test/auth/test_pytest.py

feat: Support custom auth from `requests`

---

docs/changelog.rst
docs/cli.rst
docs/python.rst
pyproject.toml
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
src/schemathesis/cli/context.py
src/schemathesis/cli/output/default.py
src/schemathesis/lazy.py
src/schemathesis/models.py
src/schemathesis/schemas.py
src/schemathesis/specs/graphql/loaders.py
src/schemathesis/specs/openapi/loaders.py
src/schemathesis/throttling.py
test/cli/test_callbacks.py
test/cli/test_commands.py
test/specs/openapi/test_validation.py
test/test_lazy.py
test/test_rate_limit.py

feat: Throttling

---

docs/changelog.rst
pyproject.toml

chore: Support `requests<3`

---

.github/workflows/build.yml
docs/changelog.rst
pyproject.toml
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
test/cli/test_commands.py
test/runner/test_runner.py
test/test_dereferencing.py
test/test_pytest.py

fix: Broken `--report` CLI argument under `click>=8.1.4`

---

docs/changelog.rst
src/schemathesis/runner/impl/core.py
test/data/petstore_v2.yaml
test/data/petstore_v3.yaml

Hi @Stranger6667, this is my first PR to the project. I fixed some minor typos.

chore: fix typos

---

docs/changelog.rst
docs/cli.rst
src/schemathesis/cli/__init__.py
test/cli/test_commands.py

- resolves #1170 
- updated run and replay function
- modified affected test cases
- modified doc

feat: Support for colored output from docker container

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/context.py
src/schemathesis/cli/output/default.py
src/schemathesis/constants.py
src/schemathesis/exceptions.py
src/schemathesis/loaders.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/events.py
src/schemathesis/service/serialization.py
src/schemathesis/specs/graphql/loaders.py
src/schemathesis/specs/openapi/loaders.py
src/schemathesis/utils.py
test/auth/test_pytest.py
test/cli/output/test_default.py
test/cli/test_asgi.py
test/cli/test_checks.py
test/cli/test_commands.py
test/code_samples/test_curl.py
test/loaders/test_common.py
test/loaders/test_openapi.py
test/runner/test_events.py
test/runner/test_runner.py
test/service/test_serialization.py
test/specs/graphql/test_basic.py
test/specs/openapi/test_stateful.py
test/test_asgi.py
test/test_models.py
test/test_schemas.py

chore: Enhance CLI output for schema loading and internal errors

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
test/cli/test_commands.py
test/cli/test_crashes.py
test/specs/openapi/test_stateful.py

chore: Disable the "explain" Hypothesis phase

---

docs/changelog.rst
docs/compatibility.rst
src/schemathesis/fixups/__init__.py
src/schemathesis/fixups/fast_api.py
src/schemathesis/fixups/utf8_bom.py
src/schemathesis/hooks.py
src/schemathesis/specs/openapi/loaders.py
test/test_asgi.py
test/test_fixups.py

feat: Automatic FastAPI fixup injecting for ASGI loaders

---

docs/changelog.rst
docs/extending.rst
docs/graphql.rst
src/schemathesis/extra/pytest_plugin.py
src/schemathesis/hooks.py
src/schemathesis/lazy.py
src/schemathesis/schemas.py
src/schemathesis/specs/graphql/schemas.py
src/schemathesis/specs/openapi/schemas.py
test/hooks/test_filter_operations.py

To conditionally include or exclude specific API operations from being tested
Resolves #1754

feat: New `filter_operations` hook

---

docs/auth.rst
docs/changelog.rst
src/schemathesis/auths.py
test/auth/test_cli.py
test/auth/test_provider.py
test/auth/test_pytest.py

chore!: Add `case` as the first argument to `AuthContext.set`.

---

docs/changelog.rst
src/schemathesis/cli/callbacks.py
src/schemathesis/utils.py
test/cli/test_commands.py

fix: Confusing error message when trying to load schema from a non-existing file

---

docs/continuous_integration.rst
docs/faq.rst
docs/recipes.rst

Update documentation in accordance with issue #1691 
Closes #1691
Precedent `docs` commits were not added to the changelog so I gessed I should not do it either. I am correct?  
This is not directly related to the content of the PR but I wanted to share some issues I had while contributing documentation so that it can be fixed. This my first time using Sphinx so maybe it's just something I didn't do properly.
1 - There is no instruction on how  to preview the changes to the documentation in the contribution guidelines. Adding a simple section with something like `cd docs/ && make html && python -m http.server -d _build/html/` would make it easier.  
2 - `sphinx-click` and `sphinx-rtd-theme` are not in the pyproject.toml docs dependencies and I couldn't build the documentation without …

docs: add why is localhost slow on windows to faq

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/runner/serialization.py
src/schemathesis/utils.py
test/code_samples/test_curl.py
test/code_samples/test_python.py

fix: Reflect disabled TLS verification in generated code samples

---

docs/changelog.rst
src/schemathesis/_hypothesis.py
src/schemathesis/cli/output/default.py
src/schemathesis/exceptions.py
src/schemathesis/extra/pytest_plugin.py
src/schemathesis/lazy.py
src/schemathesis/models.py
src/schemathesis/runner/impl/core.py
src/schemathesis/schemas.py
src/schemathesis/specs/graphql/schemas.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/parameters.py
src/schemathesis/specs/openapi/schemas.py
src/schemathesis/specs/openapi/security.py
src/schemathesis/stateful.py
test/cli/test_commands.py
test/conftest.py
test/runner/test_checks.py
test/runner/test_runner.py
test/test_errors.py
test/test_hypothesis.py
test/test_lazy.py
test/test_parameters.py
test/test_parametrization.py
test/test_recoverable_errors.py
test/test_schemas.py

chore: Improve error messages for certain schema errors

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/exceptions.py
src/schemathesis/specs/openapi/schemas.py
test/cli/test_commands.py
test/test_recoverable_errors.py

chore: Improve error messages for JSON pointer resolution errors

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/models.py
src/schemathesis/runner/serialization.py
src/schemathesis/utils.py
test/cli/output/test_default.py
test/cli/test_commands.py
test/code_samples/test_curl.py
test/code_samples/test_python.py
test/conftest.py
test/specs/openapi/test_stateful.py
test/test_models.py
test/test_pytest.py

chore: Refined generated reproduction code and shortened `X-Schemathesis-TestCaseId` for easier debugging

---

docs/changelog.rst
src/schemathesis/parameters.py
test/specs/openapi/parameters/test_simple_payloads.py

chore: Added `contains` method to `ParameterSet` for easier parameter checks in hooks

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/code_samples.py
src/schemathesis/models.py
src/schemathesis/runner/serialization.py
test/code_samples/test_python.py
test/runner/test_runner.py

Also, some further changes that needed for #1794

perf: Optimize event data emission by postponing code sample generation

---

test/code_samples/conftest.py
test/code_samples/test_curl.py
test/code_samples/test_python.py
test/conftest.py

test: More tests for generated cURL commands

---

docs/experimental.rst

🚨Please review the [Contributing Guidelines](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.rst).
Briefly describe your changes.

docs: Update experimental.rst

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/exceptions.py
src/schemathesis/runner/serialization.py
test/__snapshots__/test_hypothesis/test_health_check_failed_large_base_example.raw
test/auth/test_cli.py
test/cli/__snapshots__/test_commands/test_hypothesis_failed_event[real-Open API 2.0-1].raw
test/cli/__snapshots__/test_commands/test_hypothesis_failed_event[real-Open API 2.0-2].raw
test/cli/__snapshots__/test_commands/test_hypothesis_failed_event[real-Open API 3.0-1].raw
test/cli/__snapshots__/test_commands/test_hypothesis_failed_event[real-Open API 3.0-2].raw
test/cli/__snapshots__/test_commands/test_hypothesis_failed_event[wsgi-Open API 2.0-1].raw
test/cli/__snapshots__/test_commands/test_hypothesis_failed_event[wsgi-Open API 2.0-2].raw
test/cli/__snapshots__/test_commands/test_hypothesis_failed_event[wsgi-Open API 3.0-1].raw
test/cli/__snapshots__/test_commands/test_hypothesis_failed_event[wsgi-Open API 3.0-2].raw
test/cli/test_commands.py
test/conftest.py
test/contrib/test_unique_data.py
test/runner/test_runner.py
test/test_hypothesis.py

chore: Unified CLI messages for errors arising from Hypothesis-related issues

---

docs/changelog.rst
src/schemathesis/exceptions.py
test/apps/openapi/_aiohttp/__init__.py
test/cli/__snapshots__/test_commands/test_chunked_encoding_error[Open API 3.0].raw
test/cli/test_commands.py

chore: Handle `ChunkedEncodingError`

---

docs/changelog.rst
src/schemathesis/cli/output/default.py
src/schemathesis/runner/impl/core.py
src/schemathesis/specs/openapi/schemas.py
test/cli/test_commands.py
test/conftest.py
test/runner/test_checks.py
test/test_models.py

chore: Try to validate JSON data even if there is no proper `Content-Type` header

---

docs/changelog.rst
src/schemathesis/specs/graphql/scalars.py
src/schemathesis/specs/graphql/schemas.py
test/specs/graphql/__snapshots__/test_custom_scalars/test_built_in_scalars_in_cli.raw
test/specs/graphql/__snapshots__/test_custom_scalars/test_custom_scalar_in_cli.raw
test/specs/graphql/test_custom_scalars.py

feat: Extra GraphQL scalar strategies

---

docs/changelog.rst
docs/cli.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
src/schemathesis/internal/validation.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/override.py
src/schemathesis/schemas.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/stateful/__init__.py
test/cli/__snapshots__/test_commands/test_run_output[args24].raw
test/cli/__snapshots__/test_commands/test_run_output[args26].raw
test/cli/__snapshots__/test_commands/test_run_output[args27].raw
test/cli/__snapshots__/test_commands/test_run_output[args28].raw
test/cli/__snapshots__/test_commands/test_run_output[args29].raw
test/cli/__snapshots__/test_commands/test_run_output[args30].raw
test/cli/__snapshots__/test_commands/test_run_output[args31].raw
test/cli/__snapshots__/test_commands/test_run_output[args32].raw
test/cli/__snapshots__/test_commands/test_run_output[args33].raw
test/cli/__snapshots__/test_commands/test_run_output[args34].raw
test/cli/test_commands.py

feat: CLI options for overriding Open API parameters in test cases

---

docs/changelog.rst
src/schemathesis/parameters.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/examples.py
src/schemathesis/specs/openapi/parameters.py
test/apps/openapi/schema.py
test/specs/openapi/test_examples.py
test/specs/openapi/test_parameters.py
test/test_hypothesis.py
test/test_parametrization.py

Resolves #921
Resolves #1320
Fixes #1360 
Resolves #1730

chore: Rework examples in Open API

---

docs/changelog.rst
src/schemathesis/transports/content_types.py
test/apps/openapi/_aiohttp/handlers.py
test/apps/openapi/_flask/__init__.py
test/specs/openapi/test_serializing.py

chore: Avoid using the deprecated `cgi` module

---

docs/changelog.rst
docs/python.rst
src/schemathesis/_override.py
src/schemathesis/cli/__init__.py
src/schemathesis/extra/pytest_plugin.py
src/schemathesis/runner/__init__.py
src/schemathesis/runner/impl/core.py
src/schemathesis/specs/openapi/schemas.py
test/test_pytest.py

feat: A way to override Open API parameters the `pytest` integration

---

.github/workflows/build.yml
.pre-commit-config.yaml
tox.ini

chore: Bump Python version in pre-commit & tox

---

docs/changelog.rst
docs/python.rst
src/schemathesis/schemas.py
src/schemathesis/specs/graphql/schemas.py
src/schemathesis/specs/openapi/schemas.py
test/conftest.py
test/hooks/test_hooks.py
test/loaders/test_graphql.py
test/specs/graphql/test_basic.py
test/specs/graphql/test_custom_scalars.py

fix: Inability to access individual operations in GraphQL schema objects

---

docs/changelog.rst
docs/python.rst
src/schemathesis/schemas.py
test/specs/graphql/test_basic.py
test/specs/openapi/test_schemas.py

feat: Shortcut to create strategies for all operations or a subset of them

---

docs/changelog.rst
src/schemathesis/specs/graphql/schemas.py
test/loaders/test_graphql.py

fix: Incorrect base URL handing for GraphQL schemas

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/constants.py
test/cli/__snapshots__/test_commands/test_run_output[args24].raw
test/cli/__snapshots__/test_commands/test_run_output[args35].raw
test/cli/__snapshots__/test_commands/test_run_output[args36].raw
test/cli/test_commands.py

feat: `--hypothesis-no-phases` CLI option to disable Hypothesis testing phases

---

docs/changelog.rst
docs/stateful.rst
src/schemathesis/constants.py
src/schemathesis/stateful/state_machine.py
test/specs/openapi/test_stateful.py

chore: Clarify error message when a state machine has no transitions

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/cli/probes.py
src/schemathesis/runner/impl/core.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/formats.py
test/cli/__snapshots__/test_commands/test_null_byte_in_header_probe.raw
test/cli/test_commands.py
test/cli/test_probes.py
test/conftest.py

feat: Run automatic probes

---

docs/changelog.rst
src/schemathesis/specs/openapi/security.py
test/specs/openapi/test_security.py

fix: Not resolving references in nested security schemes

---

docs/changelog.rst
pyproject.toml
src/schemathesis/_dependency_versions.py
src/schemathesis/_rate_limiter.py
src/schemathesis/schemas.py
src/schemathesis/throttling.py
test/test_lazy.py
test/test_rate_limit.py

chore: Support `pyrate-limiter>=3.0`

---

docs/api.rst
docs/python.rst
test/experimental/test_openapi_3_1.py
test/specs/graphql/test_pytest.py
test/test_parameters.py
test/test_pytest.py
test/test_serialization.py

docs: Update docs on asgi / wsgi integrations

---

docs/changelog.rst
docs/cli.rst
src/schemathesis/cli/junitxml.py
src/schemathesis/cli/output/default.py
src/schemathesis/cli/reporting.py
src/schemathesis/runner/serialization.py
test/cli/test_junitxml.py

Ref: https://github.com/schemathesis/schemathesis/discussions/2060

feat: Extend JUnit

---

docs/changelog.rst
docs/extending.rst
src/schemathesis/__init__.py
src/schemathesis/generation/__init__.py
src/schemathesis/runner/impl/core.py
src/schemathesis/specs/openapi/_hypothesis.py
test/specs/openapi/test_hypothesis.py

feat: Expose an option to adjust header generation

---

docs/changelog.rst
src/schemathesis/cli/__main__.py
test/cli/test_commands.py

feat: support for `python -m schemathesis.cli`

---

docs/changelog.rst
pyproject.toml

chore: Support anyio>=4

---

docs/changelog.rst
src/schemathesis/transports/__init__.py

fix: Supporting non-Starlette ASGI apps

---

docs/changelog.rst
src/schemathesis/specs/openapi/_hypothesis.py
test/test_asgi.py

fix: Not respecting `allow_x00=False` in headers and cookies

---

docs/changelog.rst
src/schemathesis/exceptions.py

fix: Internal error when building an error message for some network-related issues

---

docs/changelog.rst
src/schemathesis/exceptions.py

chore: Improve error messages on MaxRetryError

---

docs/changelog.rst
src/schemathesis/extra/pytest_plugin.py
test/cli/test_commands.py
test/hooks/test_hooks.py
test/specs/openapi/test_stateful.py

chore: Migrate to new-style `pytest` hooks

---

docs/changelog.rst
src/schemathesis/failures.py
test/cli/__snapshots__/test_commands/test_response_schema_conformance_deduplication[real-Open API 2.0].raw
test/cli/__snapshots__/test_commands/test_response_schema_conformance_deduplication[real-Open API 3.0].raw
test/cli/__snapshots__/test_commands/test_response_schema_conformance_deduplication[wsgi-Open API 2.0].raw
test/cli/__snapshots__/test_commands/test_response_schema_conformance_deduplication[wsgi-Open API 3.0].raw

chore: Show sub-schema location in response_schema_conformance failure messages

---

docs/changelog.rst
src/schemathesis/specs/openapi/schemas.py
test/data/relative_files/components/parameters.yaml
test/data/relative_files/components/responses.yaml
test/data/relative_files/components/schemas.yaml
test/data/relative_files/main.yaml
test/data/relative_files/paths/user-account.yaml
test/test_schemas.py

This fixes Internal error during $ref resolve when using relative file paths.

Fix openapi relative ref

---

docs/changelog.rst
src/schemathesis/cli/reporting.py
test/cli/__snapshots__/test_checks/test_deduplication_on_sanitized_header.raw
test/cli/test_checks.py

fix: Incorrect test case reporting when code samples contain a single sanitized parameter

---

docs/changelog.rst
src/schemathesis/models.py
test/cli/test_cassettes.py

fix: Incorrect test case ids stored in VCR cassettes

---

docs/changelog.rst
docs/cli.rst
pyproject.toml
src/schemathesis/cli/__init__.py
src/schemathesis/cli/callbacks.py
src/schemathesis/cli/cassettes.py
src/schemathesis/models.py
test/apps/cp1252_app.py
test/cli/__snapshots__/test_commands/test_run_output[args24].raw
test/cli/__snapshots__/test_commands/test_run_output[args37].raw
test/cli/test_cassettes.py
test/cli/test_commands.py
test/runner/test_probes.py
test/runner/test_runner.py
test/test_sanitizing_output.py

feat: Support HAR formats for cassettes

---

docs/changelog.rst
src/schemathesis/specs/openapi/security.py
test/__snapshots__/test_dereferencing/test_global_security_schemes_with_custom_scope.raw
test/test_dereferencing.py

fix: Incorrect resolution scope for global security schemes

---

docs/changelog.rst
src/schemathesis/cli/__init__.py
src/schemathesis/generation/__init__.py
src/schemathesis/specs/openapi/schemas.py
test/cli/__snapshots__/test_commands/test_run_output[args24].raw
test/cli/test_crashes.py
test/specs/openapi/test_security.py

feat: CLI option to disable generation of security parameters

---

docs/changelog.rst
src/schemathesis/specs/openapi/negative/mutations.py
test/specs/openapi/test_negative.py

fix: Generating negative test cases for path and query parameters

---

docs/changelog.rst
src/schemathesis/models.py
src/schemathesis/specs/openapi/_hypothesis.py
src/schemathesis/specs/openapi/checks.py
src/schemathesis/specs/openapi/schemas.py
test/specs/openapi/test_checks.py
test/test_direct_access.py
test/test_hypothesis.py

chore: Do not consider ignoring additional parameters as a failure in `negative_data_rejection`

---

docs/changelog.rst
src/schemathesis/runner/impl/core.py
test/cli/__snapshots__/test_commands/test_new_stateful_runner_stateful_only_with_error[Open API 3.0].raw
test/cli/test_commands.py

fix: Not reporting errors with `--experimental=stateful-only`

---

docs/changelog.rst
src/schemathesis/runner/impl/core.py
src/schemathesis/specs/openapi/stateful/__init__.py
src/schemathesis/stateful/config.py
src/schemathesis/stateful/events.py
src/schemathesis/stateful/runner.py
src/schemathesis/stateful/sink.py
src/schemathesis/stateful/state_machine.py
test/specs/openapi/stateful/test_runner.py

feat: Support for `--dry-run` in new-style stateful tests

---

docs/changelog.rst
src/schemathesis/runner/events.py
src/schemathesis/runner/serialization.py
src/schemathesis/service/serialization.py
src/schemathesis/stateful/events.py
test/cli/test_commands.py
test/cli/test_crashes.py
test/service/test_extensions.py
test/service/test_serialization.py

fix: Internal error when saving debug logs with `--experimental=stateful-test-runner` or `--experimental=schema-analysis` enabled

---

docs/changelog.rst
docs/cli.rst
example/README.md
src/schemathesis/cli/__init__.py
src/schemathesis/filters.py
test/cli/__snapshots__/test_commands/test_deprecated_filters[Open API 3.0].raw
test/cli/__snapshots__/test_commands/test_duplicated_filters[Open API 3.0].raw
test/cli/__snapshots__/test_commands/test_run_output[args24].raw
test/cli/test_commands.py

Python API will come as a separate PR

feat: Flexible operations filter

---

docs/changelog.rst
docs/python.rst
src/schemathesis/filters.py
src/schemathesis/lazy.py
src/schemathesis/schemas.py
src/schemathesis/specs/openapi/loaders.py
test/filters/test_matching.py
test/test_lazy.py

Resolves #703
Resolves #819 
Resolves #1398

feat: Python API for filters

---

docs/changelog.rst
docs/cli.rst
docs/python.rst
src/schemathesis/cli/__init__.py
src/schemathesis/filters.py
test/apps/openapi/schema.py
test/cli/__snapshots__/test_commands/test_filter_by[Open API 3.0---exclude-by=x-property != 42].raw
test/cli/__snapshots__/test_commands/test_filter_by[Open API 3.0---include-by=x-property == 42].raw
test/cli/__snapshots__/test_commands/test_invalid_filter[Open API 3.0].raw
test/cli/__snapshots__/test_commands/test_run_output[args24].raw
test/cli/test_commands.py
test/filters/test_expressions.py

feat: A way to filter API operations by an expression in CLI

---

docs/changelog.rst
src/schemathesis/specs/openapi/examples.py
test/specs/openapi/test_examples.py

fix: Ignoring nested examples

---

docs/changelog.rst
src/schemathesis/cli/reporting.py
test/cli/test_reporting.py

fix: Internal error in CLI output when some of test cases has no responses due to timeout

---

docs/changelog.rst
src/schemathesis/specs/openapi/examples.py
src/schemathesis/stateful/runner.py
test/cli/test_reporting.py
test/specs/openapi/test_examples.py

fix: Incorrect handling of `allOf` subschemas in testing explicit examples

---

docs/changelog.rst
docs/cli.rst
docs/python.rst
src/schemathesis/exceptions.py
src/schemathesis/failures.py
src/schemathesis/models.py
src/schemathesis/specs/openapi/checks.py
src/schemathesis/specs/openapi/links.py
src/schemathesis/stateful/config.py
test/runner/test_events.py
test/specs/graphql/test_basic.py
test/specs/openapi/stateful/conftest.py
test/specs/openapi/stateful/test_runner.py
test/specs/openapi/stateful/test_stateful.py
test/test_models.py
test/test_sanitizing_output.py

It verifies that a freshly created resource is available in related API operations.

feat: The `ensure_resource_availability` check

---

docs/changelog.rst
pyproject.toml
src/schemathesis/specs/openapi/schemas.py
test/runner/test_checks.py

feat: Enable string format verification in response conformance checks

---

docs/auth.rst
docs/changelog.rst
src/schemathesis/auths.py
test/auth/test_provider.py

feat: Control over cache key in custom auth implementation

---

docs/changelog.rst
src/schemathesis/specs/openapi/checks.py
src/schemathesis/specs/openapi/links.py
src/schemathesis/stateful/__init__.py
src/schemathesis/stateful/config.py
src/schemathesis/stateful/state_machine.py
test/apps/openapi/schema.py
test/auth/test_provider.py
test/cli/__snapshots__/test_commands/test_stateful_explicit_examples_with_filters[Open API 3.0].raw
test/cli/test_commands.py
test/conftest.py

fix: Filters being ignored in the old-style stateful test runner

---

docs/changelog.rst
docs/extending.rst
src/schemathesis/hooks.py
src/schemathesis/schemas.py
src/schemathesis/specs/openapi/links.py
test/hooks/test_filters.py

feat: Filters for hooks

---

docs/changelog.rst
docs/cli.rst
docs/python.rst
src/schemathesis/cli/callbacks.py
src/schemathesis/internal/transformation.py
src/schemathesis/specs/openapi/checks.py
src/schemathesis/specs/openapi/schemas.py
src/schemathesis/specs/openapi/stateful/__init__.py
test/cli/test_commands.py
test/runner/test_checks.py

feat: Verify header schema conformance

---

docs/changelog.rst
src/schemathesis/specs/openapi/checks.py
src/schemathesis/transports/__init__.py
test/specs/openapi/test_ignored_auth.py

fix: Not using the proper session in ignored_auth

---

docs/changelog.rst
src/schemathesis/cli/cassettes.py
src/schemathesis/models.py
src/schemathesis/runner/impl/context.py
src/schemathesis/runner/impl/core.py
src/schemathesis/runner/impl/solo.py
src/schemathesis/runner/impl/threadpool.py
src/schemathesis/runner/serialization.py
src/schemathesis/sanitization.py
test/cli/test_cassettes.py
test/conftest.py

feat: Support for saving the generated data into a cassette when `--dry-run` is provided

---

docs/changelog.rst
src/schemathesis/auths.py
src/schemathesis/models.py
src/schemathesis/specs/openapi/checks.py
test/specs/openapi/test_ignored_auth.py

fix: False positive in ignored_auth when custom auth is present

---

docs/changelog.rst
src/schemathesis/internal/checks.py
src/schemathesis/stateful/runner.py
src/schemathesis/stateful/validation.py
test/specs/openapi/__snapshots__/test_ignored_auth/test_stateful_in_cli_no_error[Open API 3.0-False].raw
test/specs/openapi/__snapshots__/test_ignored_auth/test_stateful_in_cli_no_error[Open API 3.0-True].raw
test/specs/openapi/stateful/conftest.py
test/specs/openapi/stateful/test_runner.py
test/specs/openapi/test_ignored_auth.py

fix: False positive in ignored_auth in stateful test runner

---

docs/changelog.rst
src/schemathesis/models.py
test/test_models.py

Fix `Case.call_and_validate`

---

docs/changelog.rst
src/schemathesis/hooks.py
src/schemathesis/models.py
src/schemathesis/parameters.py
src/schemathesis/runner/impl/context.py
src/schemathesis/schemas.py
src/schemathesis/specs/openapi/parameters.py
src/schemathesis/transports/__init__.py

fix: Hypothesis compatibility

---

src/schemathesis/cli/__init__.py
src/schemathesis/cli/cassettes.py
src/schemathesis/cli/debug.py
src/schemathesis/cli/handlers.py
src/schemathesis/cli/junitxml.py
src/schemathesis/cli/output/default.py
src/schemathesis/cli/output/short.py
src/schemathesis/runner/context.py
src/schemathesis/runner/control.py
src/schemathesis/runner/core.py
src/schemathesis/runner/events.py
src/schemathesis/runner/phases/analysis.py
src/schemathesis/runner/phases/probes.py
src/schemathesis/runner/phases/unit/__init__.py
src/schemathesis/service/report.py
src/schemathesis/service/serialization.py
src/schemathesis/specs/openapi/stateful/statistic.py
src/schemathesis/stateful/sink.py
test-corpus/test_corpus.py
test/cli/__snapshots__/test_commands/test_custom_cli_option[Open API 3.0].raw
test/cli/output/test_default.py
test/cli/test_commands.py
test/runner/test_runner.py
test/service/test_cli.py
test/service/test_report.py
test/service/test_serialization.py
test/specs/openapi/test_ignored_auth.py
test/utils.py

refactor: Events

---

docs/changelog.rst
src/schemathesis/internal/checks.py

chore: Add HTTP 428 to the negative_data_rejection defaults

---

docs/changelog.rst
src/schemathesis/specs/openapi/patterns.py
test/specs/openapi/test_patterns.py

fix: Incorrect quantifiers merging for some patterns

---

CHANGELOG.md
src/schemathesis/specs/openapi/references.py
test/specs/openapi/__snapshots__/test_patterns/test_response_schema_is_not_mutated.raw
test/specs/openapi/test_patterns.py

fix: Do not mutate patterns in response validation schemas

---

CHANGELOG.md
src/schemathesis/generation/hypothesis/builder.py
test/specs/openapi/stateful/test_engine.py

fix: Compatibility with hypothesis >= 6.131.4

---

CHANGELOG.md
src/schemathesis/cli/commands/run/handlers/junitxml.py
test/cli/__snapshots__/test_commands/test_rediscover_the_same_failure_in_different_phases_and_store_junit[Open API 3.0].raw
test/cli/test_commands.py

fix: Internal error on building a JUnit report if the same failures appear multiple times across multiple test phases

---

CHANGELOG.md
benches/schema.py
src/schemathesis/cli/commands/run/handlers/output.py
src/schemathesis/core/errors.py
src/schemathesis/engine/errors.py
src/schemathesis/engine/events.py
src/schemathesis/engine/phases/stateful/_executor.py
src/schemathesis/engine/phases/unit/_executor.py
test/cli/__snapshots__/test_commands/test_app_crash.raw
test/cli/__snapshots__/test_commands/test_multiple_errors.raw
test/cli/__snapshots__/test_commands/test_partial_response.raw
test/cli/__snapshots__/test_commands/test_stateful_crash.raw
test/cli/test_commands.py
test/fixtures/app_runner.py
test/specs/openapi/stateful/test_cli.py

chore: Report cURL commands for some network-level errors

---

CHANGELOG.md
src/schemathesis/core/errors.py
src/schemathesis/generation/case.py
src/schemathesis/generation/hypothesis/builder.py
src/schemathesis/pytest/plugin.py
src/schemathesis/specs/openapi/schemas.py
test/cli/__snapshots__/test_checks/test_format_parameter_csv_response.raw
test/cli/test_checks.py
test/test_pytest.py

chore: Cleanup pytest output

---

CHANGELOG.md
src/schemathesis/openapi/generation/filters.py

chore: Generate at least one non-NULL character in path parameters

---

mkdocs.yml

🚨Please review the [Contributing Guidelines](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.md).
Fix typo in doc.

docs: Fix typo

---

CHANGELOG.md
src/schemathesis/cli/commands/run/handlers/junitxml.py

🚨Please review the [Contributing Guidelines](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.md).
Briefly describe your changes.

Add encoding to junit output

---

src/schemathesis/cli/commands/run/handlers/junitxml.py

🚨Please review the [Contributing Guidelines](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.md).
Briefly describe your changes.

fix: JUnit encoding again

---

CHANGELOG.md
src/schemathesis/cli/commands/run/handlers/output.py
src/schemathesis/engine/phases/probes.py
test/cli/__snapshots__/test_commands/test_connection_error[Open API 2.0-1].raw
test/cli/__snapshots__/test_commands/test_connection_error[Open API 2.0-2].raw
test/cli/__snapshots__/test_commands/test_connection_error[Open API 3.0-1].raw
test/cli/__snapshots__/test_commands/test_connection_error[Open API 3.0-2].raw
test/cli/__snapshots__/test_commands/test_group_errors.raw
test/cli/__snapshots__/test_commands/test_multiple_errors.raw
test/cli/__snapshots__/test_commands/test_proxy_error[Open API 3.0].raw
test/cli/__snapshots__/test_commands/test_read_content_timeout[Open API 3.0].raw
test/specs/openapi/__snapshots__/test_examples/test_network_error_with_flaky_generation.raw
test/specs/openapi/stateful/__snapshots__/test_cli/test_proxy_error[Open API 3.0].raw
test/specs/openapi/stateful/__snapshots__/test_cli/test_stateful_only_with_error[Open API 3.0].raw

chore: Do not display API probing errors in CLI output

---

CHANGELOG.md
src/schemathesis/engine/errors.py

chore: Display cURL code samples on more network errors

---

CHANGELOG.md
benches/coverage_phase.py
src/schemathesis/generation/coverage.py
src/schemathesis/generation/hypothesis/builder.py
test/coverage/test_combinations.py
test/coverage/test_phase.py
test/specs/openapi/__snapshots__/test_checks/test_missing_required_header[success-Authorization-200].raw
test/specs/openapi/__snapshots__/test_checks/test_missing_required_header[success-X-API-Key-1-406].raw
test/specs/openapi/stateful/test_engine.py

Resolves https://github.com/schemathesis/schemathesis/issues/2900
Resolves https://github.com/schemathesis/schemathesis/issues/2913
Resolves https://github.com/schemathesis/schemathesis/issues/2906

fix: Negative test cases with invalid parameters mistakenly becoming positive test cases

---

CHANGELOG.md
src/schemathesis/generation/hypothesis/builder.py
src/schemathesis/specs/openapi/schemas.py
test/coverage/test_phase.py

fix: Incorrect serialization of parameters with nested structures during the coverage phase

---

CHANGELOG.md
src/schemathesis/specs/openapi/stateful/__init__.py
test/specs/openapi/stateful/test_engine.py

fix: Set correct data generation mode for stateful test cases if after adding stateful data, a negative test case becomes positive

---

CHANGELOG.md
docs/reference/configuration.md
src/schemathesis/config/_error.py
src/schemathesis/config/schema.json
test/config/__snapshots__/test_config/test_configs[common.incorrect-workers].raw
test/config/__snapshots__/test_doc_examples/test_configs[workers_auto_allocate_workers].raw
test/config/configs/common/incorrect-workers.toml
test/config/test_doc_examples.py

fix: `workers = "auto"` being incorrectly rejected in configuration files

---

test/cli/__snapshots__/test_checks/test_negative_data_rejection_array_of_strings_boolean_collision.raw
test/cli/test_checks.py

Resolves #2913
Originally resolved in #3129

test: additional test for #2913
