schemathesis/schemathesis

- src/schemathesis/parametrizer.py
When using the project with Flask, it raises `RuntimeError` on `hasattr` check. I think, `is_schemathesis_test` check should be stable against all exceptions in `__getattr__` of the test function because it means that `_schema_parametrizer` wasn't explicitly specified by Schemathesis. That's not the last problem with it but step towards to integration of the project with uninitialized Flask app.
> Catch exceptions in hasattr checks

- README.rst
- src/schemathesis/commands.py
- src/schemathesis/runner.py
- test/test_commands.py
- test/test_runner.py
Closes #96 
TODO:
I took `--auth` format from `httpie`, as the next steps we can add digest auth in the way similar to `httpie`
and `--header` format is from `curl`. also it could be similar to approach with prompting for a password but it is not that important now. What do you think?
> [WIP] Add authorization to runner

- pyproject.toml
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/validators.py
- test/cli/test_commands.py
- test/cli/test_validators.py
Moved validators to a separate module, add `hypothesis` tests.
The lines were actually covered, but the data is not collected probably because of `CLIRunner` behavior
> Restructure CLI & add more tests

- src/schemathesis/cli/__init__.py
- src/schemathesis/utils.py
- test/cli/test_commands.py
- test/test_utils.py
It was broken if no endpoints/methods were used in CLI as the value for endpoints/methods was `()` which than was passed to `should_skip_method` and `should_skip_endpoint`.
> CLI: Fix test generation if no filters are used

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/output.py
- src/schemathesis/runner.py
- src/schemathesis/utils.py
- test/cli/test_commands.py
- test/cli/test_output.py
- test/test_runner.py
- Fix https://github.com/kiwicom/schemathesis/issues/29
This is what the output looks like:
```
Running schemathesis test cases ...
------------------------------- FALSIFYING EXAMPLES ----------------------------
Falsifying example: single_test(case=Case(path='/ping', method='GET', path_parameters={}, headers={}, cookies={}, query={}, body={}, form_data={}), session=<requests.sessions.Session at 0x7fd21c90f090>, url='http://localhost:8080', checks=(
<function schemathesis.runner.not_a_server_error>), stats=StatsCollector(data=defaultdict(<class 'collections.Counter'>, {'not_a_server_error': Counter({'total': 100, 'ok': 98, 'error': 2}))})))
--------------------------------------------------------------------------------
----------------------------------- SUMMARY …
```
> cli: Add execution results with colors

- poetry.lock
- pyproject.toml
- src/schemathesis/__init__.py
- src/schemathesis/runner.py
- test/test_runner.py
> Send user-agent via CLI runner

- src/schemathesis/cli/output.py
- test/cli/test_commands.py
- test/test_direct_access.py
Got it from `mutmut` run.
It seems like `title` should be required argument without a default value which also simplifies the logic a little bit
> Slight refactoring

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/output.py
- src/schemathesis/utils.py
- test/cli/test_output.py
It is needed to write our own text to stdout during the execution of the tests (#125 )
> Capture Hypothesis output separately, without capturing the whole stdout during CLI run.

- src/schemathesis/loaders.py
The idea was to re-use `session`  from `execute_from_schema`, but it is not the case. Thus, removing it for now - we can implement it completely later
> Remove `session` argument `from_uri`, since it is not used as planned

- docs/changelog.rst
- test/app.py
> Fix test server generated wrong schema when ``endpoints`` option is passed via CLI.

- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/output.py
- src/schemathesis/runner/events.py
- test/cli/test_commands.py
- test/cli/test_output.py
> Fix percentage output & make CLI output closer to pytest style

- src/schemathesis/cli/output.py
- src/schemathesis/models.py
- src/schemathesis/runner/__init__.py
- src/schemathesis/runner/events.py
- test/cli/test_commands.py
- test/cli/test_output.py
- test/test_runner.py
Overview of the changes:
- results for checks in the single Hypothesis test are collected as a list of results, rather than aggregation
- removed `suppress(AssertionError` since we have `try/except` with additional logic
- results for different tests are collected as separate results
- Renaming to reflect the changes in the structure
This restructure unblocks development of:
- Showing formatted falsifying examples grouped by method/endpoint in the "HYPOTHESIS OUTPUT" section
- Showing detailed statistic per method/endpoint in the "SUMMARY" section
For these features, we need a structured, non-aggregated output from the runner, which this PR implements
> Restructure CLI statistic

- docs/changelog.rst
- src/schemathesis/runner/__init__.py
- test/test_runner.py
> Fix handling for errors other than `AssertionError` and `HypothesisException` in the runner

- docs/changelog.rst
- src/schemathesis/runner/__init__.py
- test/test_runner.py
> Fix wrong handling of `base_url` parameter in runner if it has a trailing slash

- test/conftest.py
- test/test_direct_access.py
- test/utils.py
Benchmarked with `hyperfine`. Not patched:
```
⇒  hyperfine pytest
Benchmark #1: pytest
Time (mean ± σ):     26.637 s ±  0.321 s    [User: 22.430 s, System: 0.938 s]
Range (min … max):   26.213 s … 27.140 s    10 runs
```
vs patched:
```
⇒  hyperfine pytest   
Benchmark #1: pytest
Time (mean ± σ):     24.258 s ±  0.273 s    [User: 20.051 s, System: 0.958 s]
Range (min … max):   23.969 s … 24.913 s    10 run
```
which is ~9% improvement
> Speedup tests

- test/test_hypothesis.py
It will make the collected node names list the same on each collection
and thus will make `pytest-xdist` work. Reproducible test collection is
required for it
> Sort items in `parametrize` args

- docs/changelog.rst
- src/schemathesis/cli/output.py
- src/schemathesis/models.py
- test/app/__init__.py
- test/cli/test_commands.py
> Add summary line in the CLI output with the number of passed / failed/ errored endpoint tests

- docs/changelog.rst
- src/schemathesis/runner/__init__.py
- src/schemathesis/utils.py
- test/test_runner.py
> Fix `IndexError` when Hypothesis found inconsistent test results during the test execution in runner

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/output.py
- src/schemathesis/models.py
- src/schemathesis/runner/__init__.py
- src/schemathesis/schemas.py
- src/schemathesis/utils.py
- test/app/__init__.py
- test/app/handlers.py
- test/cli/test_commands.py
- test/cli/test_output.py
- test/test_checks.py
- test/test_hypothesis.py
- test/test_runner.py
- test/test_utils.py
> Check to verify response status & content type in CLI / Runner

- .dockerignore
- .github/workflows/master_update.yml
- .github/workflows/release.yml
- .github/workflows/scheduled.yml
- Dockerfile
- README.rst
- docs/changelog.rst
> Create a docker image for CLI

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/output.py
- src/schemathesis/models.py
- src/schemathesis/runner/__init__.py
- src/schemathesis/schemas.py
- test/cli/test_commands.py
- test/cli/test_output.py
Closes #267 
Output example:
```
=== ERRORS ===
____ GET: /api/flaky ____
hypothesis.errors.Flaky: Tests on this endpoint produce unreliable results: 
Falsified on the first call but did not on a subsequent one
Used seed       : 246442565675977375928223543448485731889
Query           : {'id': 0}
Run this Python code to reproduce this failure: 
requests.get('http://127.0.0.1:8081/api/flaky', params={'id': 0})
=== FAILURES ===
___ GET: /api/failure ____
Received a response with 5xx status code: 500
Used seed       : 313022266096038506880814748301664910156
Check           : not_a_server_error
Run this Python code to reproduce this failure: 
requests.get('http://127.0.0.1:8081/api/failure')
```
> Display seed in the CLI output.

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/extra/pytest_plugin.py
- test/test_pytest.py
> Fix pytest fixtures parametrization via `pytest_generate_tests` hook

- docs/changelog.rst
- src/schemathesis/models.py
- test/test_models.py
> Fix unclosed `requests.Session` on calling `Case.call` without passing a session explicitly

- .dockerignore
- Dockerfile
* Improve caching by just copying essential files for each stage
* Group RUN commands in as few layers as possible
* Use `poetry==1.0.0b5`, which allows avoiding the installation of the local package
* Generate `schemathesis` comand, globally accessible
* Use whitelist approach for `.dockerignore`
Apologies for not noticing that it wouldn't be easy to run it on CI during my first review
I don't fully like the solution, but unfortunately `poetry` is not yet ready for using it comfortably outside of the dev environment. Personally, when I've used poetry in the past I just ended up generating a `requirements.txt` and using that in the docker image instead... but with this changes it's enough to make it usable both in CI and locally
locally, nothing changed:
```bash
docker run --rm …
```
> build(docker): Make image more usable in CI environments

- .github/workflows/build.yml
- .github/workflows/commit.yml
- .github/workflows/master_update.yml
- .github/workflows/release.yml
- .github/workflows/scheduled.yml
Changes:
- Separated workflow for jobs that must run for change in every file (commitsar only for now)
- Updated list of files that trigger build jobs 
- Use stable version of [checkout](https://github.com/actions/checkout) action instead of master.
- Use Python 3.8 for job where it is relevant
- Use shallow clone of schemathesis repository via checkout action to reduce cloning time
- Cache poetry virtualenv where it is possible
- Use matrix to use only one parametrized tox job.
- Trigger release jobs only on published releases. Looks like `edited` release triggers only when title/description is changes, tag change creates another release event.
- Use `steps.if` syntax to decrease mumut job complexity. Behavior is the same: mutations will be displayed only if `mutmut run` step exited with …
> CI: Refator CI

- README.rst
- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/output/__init__.py
- src/schemathesis/cli/output/default.py
- src/schemathesis/cli/output/short.py
- src/schemathesis/runner/__init__.py
- src/schemathesis/runner/events.py
- src/schemathesis/schemas.py
- src/schemathesis/utils.py
- test/cli/test_commands.py
Resolves #91 
It is a very rough draft
TODO:
Probably more TODO things to come
Some benchmark of our internal service (6 endpoints):
- master branch - 158.54 seconds
- this branch - 53.4 sec in 6 worker threads
> Concurrent test execution in CLI / runner

- .github/workflows/release.yml
This is what is causing the releases to have a single entry
> chore(ci): Remove git depth limit

- test/apps/_flask/__init__.py
Don't know the root cause, but on Linux the values are not in list,
not checked the package versions precisely yet, but this check doesn't make harm
It seems that this conversion happens implicitly somewhere
> Failing tests on Mac

- test/apps/utils.py
- test/cli/test_commands.py
- test/data/petstore_v2.yaml
- test/generation/test_complex.py
- test/generation/test_primitive.py
- test/test_common_parameters.py
- test/test_dereferencing.py
- test/test_filters.py
- test/test_lazy.py
- test/test_parameters.py
- test/test_parametrization.py
- test/test_pytest.py
- test/test_required.py
- test/test_wsgi.py
- test/utils.py
Tests for `additionalItems` are removed since they are relevant to the JSONSchema, not to Open API
> Make schemas in tests compliant to the spec

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- test/test_parameters.py
> fix: Generation of invalid values in `Case.cookies`

- docs/changelog.rst
- src/schemathesis/schemas.py
- test/conftest.py
- test/test_parametrization.py
> fix: Handling examples of parameters in Open API 3.0

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/output/default.py
- src/schemathesis/runner/events.py
- src/schemathesis/utils.py
- test/cli/output/test_default.py
- test/cli/test_commands.py
> feat: `--show-error-tracebacks` CLI option to display errors' tracebacks in the output

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/callbacks.py
- src/schemathesis/utils.py
This is a fix for #399 which worked for me.
os.path is not as cool as pathlib, but in this case it has the better behaviour. Namely it doesn't throw an error on Python < 3.8
> Fixing path check in cli

- docs/changelog.rst
- src/schemathesis/loaders.py
- src/schemathesis/schemas.py
- test/cli/test_commands.py
- test/test_dereferencing.py
Fixes #418 
With `file://` schema things are much simpler
> fix: Resolving references when schema is loaded from a file on Windows

- docs/changelog.rst
- src/schemathesis/utils.py
- test/test_pytest.py
> fix: Error during `pytest` collection on objects that have custom `__getattr__` method and therefore pass `is_schemathesis` check

- docs/changelog.rst
- poetry.lock
- pyproject.toml
- test/cli/test_commands.py
> chore: Allow `werkzeug` >= 1.0.0

- docs/changelog.rst
- src/schemathesis/cli/output/default.py
- test/cli/output/test_default.py
> fix: Typo in a help message in the CLI output

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- test/runner/test_runner.py
As discussed on gitter there's currently a bug where schemathesis will allow `""` as a valid input for a required path variable. This behaviour is incorrect and fixed with this patch.
> Fixes bug where an empty string would be accepted as a required path template variable

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- test/runner/test_runner.py
Filters problematic strings containing slashes or htmlencoded `%2F`.
These strings causes problems both in WSGI and ASGI based applications.
Follow up on https://github.com/kiwicom/schemathesis/pull/439 
Related issue: https://github.com/tiangolo/fastapi/issues/1132
> fix: Filter problematic strings with slashes

- docs/changelog.rst
- src/schemathesis/__init__.py
- src/schemathesis/loaders.py
- src/schemathesis/utils.py
- test/test_loaders.py
It was deprecated for quite a while already. It is a part of clean-ups before 1.0 release
> chore: Remove deprecated `Parametrizer` class

- README.rst
- docs/changelog.rst
- src/schemathesis/runner/__init__.py
- src/schemathesis/runner/events.py
It should not be used, since `runner.prepare` provides a more flexible interface to test execution.
Ref: #442
> chore: Deprecate `runner.execute`

- docs/changelog.rst
- src/schemathesis/runner/__init__.py
- test/runner/test_runner.py
> refactor!: Remove deprecated `runner.execute`

- docs/changelog.rst
- src/schemathesis/schemas.py
- test/test_parametrization.py
> fix: Processing of explicit examples in Open API 3.0 when there are multiple parameters in the same location

- src/schemathesis/models.py
- src/schemathesis/runner/__init__.py
- src/schemathesis/runner/impl/__init__.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/runner/impl/solo.py
- src/schemathesis/runner/impl/threadpool.py
- src/schemathesis/types.py
- src/schemathesis/utils.py
- test/cli/test_commands.py
- test/runner/test_runner.py
Different runner types are placed in different modules. It is a preparation for a new runner type - `subprocess`, which will be helpful when it is not desirable to use the runner in the same thread, e.g. web app (since hypothesis runs a CPU intensive load it will affect the web thread performance). Running the whole runner in a separate process won't help much since there is no built-in way to communicate with that spawned process - this part will be implemented in a new runner type, so the client can just consume events as with any other runner type
> refactor: Restructure runner

- docs/changelog.rst
- src/schemathesis/schemas.py
- test/test_parametrization.py
> fix: Handling of fields in `paths` that are not operations, but allowed by the Open API spec

- .github/workflows/build.yml
- docs/changelog.rst
- pyproject.toml
- src/schemathesis/extra/pytest_plugin.py
- test/test_pytest.py
- tox.ini
Resolve #451 
I don't want to drop support for pytest<5.4
> fix: Pytest 5.4 warning about deprecated `Node` initialization usage

- docs/changelog.rst
- src/schemathesis/checks.py
- test/runner/test_checks.py
> fix: Precedence of `produces` keywords for Swagger 2.0 schemas

- docs/changelog.rst
- src/schemathesis/models.py
- test/cli/test_commands.py
> fix: Handling of endpoints that contain `multipart/form-data` media types in Open API 3.0 schemas

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/callbacks.py
- src/schemathesis/cli/context.py
- src/schemathesis/cli/output/default.py
- src/schemathesis/cli/output/short.py
- src/schemathesis/runner/__init__.py
- src/schemathesis/runner/events.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/runner/impl/threadpool.py
- src/schemathesis/runner/serialization.py
- src/schemathesis/utils.py
- test/cli/output/test_default.py
- test/cli/test_commands.py
- test/runner/test_checks.py
- test/runner/test_events.py
- test/runner/test_runner.py
- test/test_converter.py
- test/test_hypothesis.py
Data is mostly copied into events. It makes CLI decoupled from the runner, which
leads to a unified design of all future `runner` users.
TODO:
> refactor: Make `runner` events into serializable static objects

- src/schemathesis/runner/impl/core.py
- src/schemathesis/runner/impl/solo.py
- src/schemathesis/runner/impl/threadpool.py
Not needed since 2270e00147d90360fa0152bfb13ef380c278f38d
> refactor: Remove unused `schema` argument from runner internals

- docs/changelog.rst
- src/schemathesis/models.py
- src/schemathesis/types.py
- test/test_models.py
> fix: Code samples for schemas where `body` is defined as `{"type": "string"}`

- docs/changelog.rst
- src/schemathesis/loaders.py
- test/cli/test_commands.py
> fix: Showing error causes on internal `jsonschema` errors during input schema validation

- docs/changelog.rst
- src/schemathesis/schemas.py
- test/runner/test_runner.py
- test/test_dereferencing.py
Fixes #468 
@jeremyschiemann 
It changes `Endpoint.definition` to schemas with not resolved references, so `jsonschema.validate` won't fail. Unfortunately, it was masked with the mocking of `RECURSION_DEPTH_LIMIT` in the relevant test, so, the issue you mentioned in #468 is reproducible (hopefully).
I hope to release a new version today and would love to hear your feedback if it actually fixes the problem, which is actually my 3rd attempt on this issue :)
> fix: Recursion error in `response_schema_conformance` check

- src/schemathesis/cli/cassettes.py
- src/schemathesis/models.py
Since cassettes writer adds a certain overhead I looked for ways to improve performance.
Here some performance benchmarks I did with the current implementation (with using [hyperfine](https://github.com/sharkdp/hyperfine) on default settings and `-i` option to ignore non-zero exit codes).
The built-in test server was used with the following config:
```./test_server.sh 8081 --endpoints=success,failure,path_variable,multipart,recursive,multipart,payload,upload_file```
Command: `schemathesis run --hypothesis-max-examples=1000 --hypothesis-seed=1 --hypothesis-deadline=None http://127.0.0.1:8081/swagger.yaml` + `--store-network-log=cassette.yaml` in relevant cases
No cassettes: 11.222 s (baseline)
Current implementation with C-extension: 12.504 s (**+11.4%**)
Current implementation without …
> perf: Improve cassette writer performance

- docs/changelog.rst
- docs/usage.rst
- pyproject.toml
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/cassettes.py
- test/apps/_aiohttp/__init__.py
- test/apps/_aiohttp/handlers.py
- test/apps/_flask/__init__.py
- test/apps/utils.py
- test/cli/test_cassettes.py
- test/cli/test_commands.py
- test/conftest.py
> feat: Replay cassettes

- README.rst
- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/hooks.py
- src/schemathesis/schemas.py
- src/schemathesis/types.py
- test/test_hooks.py
This will help building strategies in hooks by providing more info. It might be helpful if the test is covering multiple endpoints and the hook should adjust strategies differently, depending on the current endpoint.
> feat: Add `context` argument to hook functions

- README.rst
- docs/changelog.rst
- docs/customization.rst
- docs/index.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/hooks.py
- src/schemathesis/models.py
- src/schemathesis/schemas.py
- src/schemathesis/types.py
- src/schemathesis/utils.py
- test/conftest.py
- test/hooks/test_deprecated.py
- test/hooks/test_hooks.py
Why a new hook system?
- Isolate & unify hook registration logic
- A more generic hooks execution logic
- Validation of registered hooks
- Register multiple hooks per name - it will allow implementing fixups. Otherwise, hooks are re-assigned and fixups (if they will use hooks) might be rewritten by user's hooks
- A more generic naming structure, now we have only hooks named by request parts names
> feat: A new generic hooks system

- poetry.lock
- pyproject.toml
Added sphinx so the documentation can be built from within the poetry venv.
**Background**  
Sphinx need to live in the same python environment as schemathesis for the [/docs/conf.py](/docs/conf.py) file to work. The most reasonable thing in my point of view is to include it as a dev-dependency.
**Motivating example**
If I develop schemathesis in a local poetry venv but try to build the docs using a global sphinx installation in another python env I will get the following results
```sh
make html
Running Sphinx v3.0.3
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
File "/…/.local/pipx/venvs/sphinx/lib/python3.8/site-packages/sphinx/config.py", line 319, in eval_config_file
execfile_(filename, namespace)
File …
```
> docs: Added sphinx as a dev dependency 

- docs/changelog.rst
- src/schemathesis/filters.py
- src/schemathesis/lazy.py
- src/schemathesis/loaders.py
- src/schemathesis/schemas.py
- test/data/simple_openapi.yaml
- test/test_filters.py
- test/test_loaders.py
trying to done  #546 
- schema.parametrize0 add new parameter `operationId`， `operationId` can is str or list
- when the schema is instantiated, a dict (schema.schema_map) record the mapping relationship between operationid and endpoint
- when call get_all_endpoints,  if has operationId than get endpoint from schema_map
> add filter parameter `operationId` 

- README.rst
- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/filters.py
- src/schemathesis/runner/__init__.py
- test/cli/test_commands.py
- test/test_loaders.py
It also fixes the case when the filter is passed, but there is no `operationId` field defined (it was failing with `TypeError`)
> feat: Add operationId filter to CLI

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/schemas.py
- test/test_parameters.py
- test/test_petstore.py
Resolves #540 
TODO:
I discovered #559 during implementation - will fix it separately
> feat: Security parameters generation

- docs/changelog.rst
- src/schemathesis/schemas.py
- test/conftest.py
- test/runner/test_checks.py
- test/test_schemas.py
> fix: Reference resolving and `nullable` handling in response schema conformance check

- test/cli/test_junitxml.py
- tox.ini
This job was installing pytest 5.4.1 instead of the latest one from `5.3.x`
> test: Fix build for pytest<5.4

- docs/changelog.rst
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/runner/serialization.py
- test/runner/test_runner.py
> fix: Display proper headers in reproduction code when headers are overridden

- docs/changelog.rst
- src/schemathesis/runner/__init__.py
- test/runner/test_runner.py
> fix: Passing `workers_num` to `ThreadPoolRunner`

- docs/changelog.rst
- src/schemathesis/_compat.py
- src/schemathesis/_hypothesis.py
- test/test_compat.py
- test/test_examples.py
- test/test_hypothesis.py
> fix: Partially generated explicit examples are always valid and can be used in requests

- docs/changelog.rst
- src/schemathesis/cli/callbacks.py
- test/cli/test_commands.py
> fix: Support for a colon symbol ('':') inside of a header value passed via CLI

- docs/changelog.rst
- src/schemathesis/specs/openapi/references.py
- test/test_dereferencing.py
> feat: Support for YAML files in references via HTTP & HTTP schemas

- .gitignore
- docs/changelog.rst
- docs/customization.rst
- src/schemathesis/hooks.py
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- test/cli/test_commands.py
- test/test_models.py
Related issue: #458 
Updates:
- Adds `add_case` hook. For each `add_case` hook and for each endpoint, an additional, duplicate test is created, and the associated Case object is passed to hook before the request is sent to the server.
Purpose:
- Used to create targeted requests. The duplicate Case objects may be altered in specific ways to target specific behavior in the API. User may test, for example, how the API behavior is affected when the rest of the request stays the same but the `Content-Type` header is set to `application/json; charset=utf8`.
Tests:
- Adds a test to ensure that one additional Case object is created for each endpoint.
- Add test to ensure that mutation of a Case in an `add_case` hook does not affect other Cases.
- Adds a test to ensure the output is formatted …
> feat: add_case hooks

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/models.py
- src/schemathesis/schemas.py
- src/schemathesis/specs/openapi/schemas.py
- src/schemathesis/specs/openapi/serialization.py
- test/specs/openapi/test_serializing.py
- test/test_hypothesis.py
- test/test_parameters.py
> feat: Support for parameters serialization formats in Open API 2 / 3

- README.rst
- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/models.py
- src/schemathesis/schemas.py
- src/schemathesis/specs/openapi/examples.py
- src/schemathesis/specs/openapi/links.py
- src/schemathesis/specs/openapi/schemas.py
- test/specs/openapi/test_examples.py
- test/test_examples.py
- test/test_hypothesis.py
Implements #589
Updates:
- add specs/openapi/examples to hold the logic for retrieving examples from endpoints
- add support for OpenAPI examples
Tests:
- add unit tests for retrieving examples from "examples"
- add tests to make sure the static_parameter objects are created correctly
Note:
- Implementation allows the "example" and "examples" keywords to be used at the same time. We get all examples from "examples", and if "example" is used also, we create one more strategy using the "example" values.
> feat: support for multiple examples

- docs/changelog.rst
- src/schemathesis/exceptions.py
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- test/cli/test_commands.py
> fix: Show exception information for test runs on invalid schemas with `--validate-schema=false` command-line option

- docs/changelog.rst
- docs/customization.rst
- src/schemathesis/hooks.py
- src/schemathesis/runner/impl/core.py
- test/cli/test_commands.py
Updates:
- Allow user to not create an additional test case by returning None
- Pass the server response from the parent case to its child cases
Purpose:
- Allows user to create additional tests conditionally. For example, user may only want to create an additional test if the parent case received a 2xx response.
> feat: pass original case's response to add_case hook

- docs/changelog.rst
- src/schemathesis/hooks.py
- src/schemathesis/schemas.py
- test/hooks/test_hooks.py
> feat: Allow register function-level hooks without passing their name as the first argument to `apply`

- docs/changelog.rst
- src/schemathesis/utils.py
- test/test_loaders.py
`pyyaml` parses numbers in scientific notation without a dot as strings:
https://github.com/yaml/pyyaml/issues/173
https://github.com/yaml/pyyaml/pull/174
This PR presents a temporary solution until the issue is resolved upstream.
> Fix schema loader to parse numbers in scientific notation

- README.rst
- docs/changelog.rst
- pyproject.toml
- src/schemathesis/cli/__init__.py
- src/schemathesis/loaders.py
- src/schemathesis/models.py
- src/schemathesis/runner/__init__.py
- src/schemathesis/runner/impl/__init__.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/runner/impl/solo.py
- src/schemathesis/runner/impl/threadpool.py
- test/apps/_fastapi/__init__.py
- test/apps/_fastapi/app.py
- test/cli/test_asgi.py
- test/cli/test_commands.py
- test/conftest.py
- test/test_asgi.py
- tox.ini
> This commit adds support to run ASGI applications directly from CLI
using --app option or in-code using from_asgi.
It is currently based on Starlette's TestClient.
Base on #512 
On the basis of this, we add some code and pass the preliminary test.
- `schemathesis.loaders.from_asgi` get schema
- `schemathesis.models.Case.call_asgi` using `starlette.testclient.TestClient` call API
> feat: Support ASGI applications

- src/schemathesis/runner/__init__.py
- test/cli/test_commands.py
When  use `--app` arguments， custom header arguments is miss.
In a project, accessing the schame require authentication, which may cause the program to fail
> fix: Passing `headers` to `loader_for_app`

- README.rst
- docs/changelog.rst
- docs/graphql.rst
- docs/index.rst
- poetry.lock
- pyproject.toml
- src/schemathesis/__init__.py
- src/schemathesis/extra/_aiohttp.py
- src/schemathesis/extra/_flask.py
- src/schemathesis/extra/_server.py
- src/schemathesis/specs/graphql/__init__.py
- src/schemathesis/specs/graphql/loaders.py
- src/schemathesis/specs/graphql/schemas.py
- test/apps/__init__.py
- test/apps/_graphql/__init__.py
- test/apps/_graphql/app.py
- test/apps/_graphql/schema.py
- test/conftest.py
- test/specs/graphql/test_basic.py
- tox.ini
WIP support for GraphQL. At the moment it is possible to create a strategy and use it in a test:
```python
schema = schemathesis.graphql.from_url("https://bahnql.herokuapp.com/graphql")
@given(case=schema.query.as_strategy()) 
@settings(deadline=None) 
def test(case): 
response = case.call() 
assert response.status_code < 500, response.content
```
Execution of the test above sometimes triggers `{"errors":[{"message":"Betriebsstellen: Failed to parse JSON","locations":[{"line":3,"column":5}],"path":["search","operationLocations"]}],"data":null}'` on a valid query :)
Roadmap:
The current implementation on the `hypothesis-graphql` side is extremely slow :( I need to find ways to speed it up. 
Also, I am not sure that it is feasible to create a more generic interface in `BaseSchema` - maybe …
> feat: GraphQL support

- src/schemathesis/specs/openapi/examples.py
- test/specs/openapi/test_examples.py
- test/test_examples.py
Before this change, `get_strategy` was able to return `None` but it wasn't possible inside `get_strategies_from_examples` because `get_static_parameters_from_examples` should have produced a list with `None`, which wasn't the case. But now, the code is re-arranged a bit, so it is statically known that `get_strategies_from_examples` won't return `None`.
> chore: Statically guarantee that the output of `get_strategies_from_examples` will not contain `None` values

- README.rst
- docs/changelog.rst
- src/schemathesis/specs/openapi/examples.py
- test/data/petstore_v2.yaml
- test/data/petstore_v3.yaml
- test/specs/openapi/test_examples.py
- test/test_dereferencing.py
- test/test_petstore.py
Related issue: #467 
Updates:
- Process property-level examples.
- Merge property-level examples with schema-level examples provided with `example` keyword.
Tests:
- Update tests that use schemas with property-level examples to reflect additional generated examples.
- Add tests for each function to generate static params from property-level examples.
> feat: support property-level examples

- docs/changelog.rst
- src/schemathesis/specs/openapi/schemas.py
- test/runner/test_checks.py
> fix: Content type conformance check for cases when Open API 3.0 schemas contain "default" response definitions

- README.rst
- docs/stateful.rst
- docs/targeted.rst
- test/apps/__init__.py
- test/apps/_aiohttp/__init__.py
- test/apps/_aiohttp/app.py
- test/apps/_flask/__init__.py
- test/apps/_flask/app.py
- test/apps/utils.py
- test/cli/test_cassettes.py
- test/cli/test_commands.py
- test/cli/test_junitxml.py
- test/conftest.py
- test/extra/test_aiohttp.py
- test/hooks/test_hooks.py
- test/runner/test_runner.py
- test/specs/openapi/test_links.py
- test/specs/openapi/test_schemas.py
- test/test_async.py
- test/test_wsgi.py
Resolves #392 
Some of the currently failing tests point to actual errors and probably I'll resolve them separately (e.g. sending multipart on OAS3)
TODO:
> test: Add Open API 3.0 test app

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/models.py
- src/schemathesis/schemas.py
- src/schemathesis/specs/openapi/schemas.py
- test/apps/_aiohttp/handlers.py
- test/apps/_flask/__init__.py
- test/apps/utils.py
- test/cli/test_commands.py
- test/runner/test_runner.py
- test/test_hypothesis.py
> fix: Handling of multipart requests for Open API 3.0 schemas

- docs/changelog.rst
- src/schemathesis/specs/openapi/_hypothesis.py
- test/test_parameters.py
> fix: Possible `UnicodeEncodeError` during generation of `Authorization` header values for endpoints with `basic` security scheme

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- test/test_hypothesis.py
> fix: `ValueError` during sending a request with test payload if the endpoint defines a parameter with type: array` and `in: formData`

- docs/changelog.rst
- src/schemathesis/specs/openapi/converter.py
- test/test_converter.py
> fix: `KeyError` during processing a schema with nullable parameters and `in: body`

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/specs/openapi/schemas.py
- test/test_hypothesis.py
> feat: Possibility to generate values for `in: formData` parameters that are non-bytes or contain non-bytes (e.g. inside an array)

- docs/changelog.rst
- src/schemathesis/specs/openapi/schemas.py
- test/test_parametrization.py
> fix: `StopIteration` during `requestBody` processing if it has empty "content" value

- .github/workflows/build.yml
- poetry.lock
- pyproject.toml
- tox.ini
That is going to remove duplication between `tox.ini` and `pyproject.toml`
> test: Install dependencies via poetry in tox runs

- README.rst
- docs/changelog.rst
- src/schemathesis/checks.py
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/specs/openapi/checks.py
- test/cli/test_commands.py
@Stranger6667  We have custom checks that are only relevant in certain circumstances. For example, we have a check that only runs an assertion when the response status code is `406`. Currently, all checks run against all responses. This is OK and still correct, but the final results may be misleading. Consider the case where we send 100 requests during testing, and we only have one response with a status code of `406`. Lets assume the above-mentioned check (that only runs when the response status code is `406`) fails for the `406` response. Before, the output would say:
406-check    99 / 100
but it would be more accurate to say:
406-check    0 / 1
Note: I updated the return type of the checks to `Optional[bool]`. `MyPy`, however, failed unless the checks explicitly returned `None` even …
> feat: run checks conditionally

- docs/changelog.rst
- src/schemathesis/specs/openapi/checks.py
- test/runner/test_checks.py
> fix: `KeyError` during the `content_type_conformance` check if the response has no `Content-Type` header

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/constants.py
- src/schemathesis/runner/impl/core.py
- test/test_pytest.py
> chore: Set the default Hypothesis's `deadline` setting for tests with `schema.parametrize` to 500 ms for consistency with the CLI behaviour

- docs/changelog.rst
- src/schemathesis/models.py
> chore: Hide `Case.endpoint` from representation

- docs/changelog.rst
- src/schemathesis/runner/impl/core.py
- test/cli/test_commands.py
> fix: Possible `IndexError` when a user-defined check raises an exception without a message

- docs/changelog.rst
- src/schemathesis/cli/output/default.py
- src/schemathesis/models.py
- src/schemathesis/runner/serialization.py
- test/cli/output/test_default.py
- test/cli/test_commands.py
This change will simplify the typing of protocols in the future and eventually allow us to make more generic structures and accommodate other specs easier
> refactor: Do not display the check name in the CLI

- docs/changelog.rst
- src/schemathesis/lazy.py
- test/test_lazy.py
Ref: #636 
It is not a complete solution for that issue but improves the behavior at least partially
> fix: Show a more precise percentage value for tests executed via `from_pytest_fixture`

- src/schemathesis/specs/graphql/schemas.py
- test/specs/graphql/test_pytest.py
Introduced in d66336ad147f9bdcd724a65e14a967307ed70cad
No changelog entry, because this version wasn't released yet
> fix: `GraphQLCase.call_and_validate` using wrong defaults

- src/schemathesis/_hypothesis.py
- test/test_pytest.py
Otherwise `case.endpoint` will be the same for all tests generated for a test function
> fix: Reusing `case` strategy if additional Hypothesis strategies are used

- docs/changelog.rst
- src/schemathesis/models.py
- src/schemathesis/specs/graphql/schemas.py
- test/cli/output/test_default.py
- test/specs/graphql/test_basic.py
- test/test_models.py
It will also make them return the `User-Agent` header value.
> refactor: Make ``as_requests_kwargs`` and ``as_werkzeug_kwargs`` reuse the same code for headers handling.

- docs/changelog.rst
- docs/cli.rst
- src/schemathesis/cli/cassettes.py
- test/cli/test_cassettes.py
Added new field to cassettes that stores information about executed checks.
Related to #702
> Store more information about executed checks in cassettes

- docs/changelog.rst
- docs/cli.rst
- src/schemathesis/cli/cassettes.py
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- test/cli/test_cassettes.py
Before this change, all statuses were taken from the overall test outcome, rather than from the check results for a particular response.
Resolves #695
> fix: Status of individual interactions in VCR cassettes

- src/schemathesis/cli/cassettes.py
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/runner/serialization.py
- test/cli/test_cassettes.py
Now they are properly escaped and not duplicated - each interaction stores their respective checks
FIxes #702
> fix: Storing check results in cassettes

- docs/changelog.rst
- src/schemathesis/cli/cassettes.py
- test/cli/test_cassettes.py
- test/conftest.py
> fix: Escaping header values in VCR cassettes

- docs/changelog.rst
- poetry.lock
- pyproject.toml
- src/schemathesis/loaders.py
- test/test_loaders.py
This patch set adds a new port parameter to .from_uri() when a base_url
is not specified but a port is, it will take the original URL and adjust
the port to the specified one.
Closes: #706
> fix(uri): allows specifying port for base_url

- test/cli/test_cassettes.py
- test/cli/test_commands.py
- test/cli/test_junitxml.py
- test/conftest.py
- test/test_lazy.py
Still need to include tests with the `hypothesis_max_examples` fixture to the scheduled run config
> test: Run more tests with higher number of examples during scheduled runs

- docs/changelog.rst
- src/schemathesis/specs/openapi/_hypothesis.py
- test/test_hypothesis.py
> perf: Speed up generation of `headers`, `cookies`, and `formData` parameters when their schemas do not define the `type` keyword

- .github/workflows/release.yml
I've updated the release action so it uses the more efficient [kaniko](https://github.com/GoogleContainerTools/kaniko) builder, and I've also changed the image organization target to the newly created `schemathesis` org and also GitHub docker registry.
> chore(ci): publish image under schemathesis org using kaniko

- docs/changelog.rst
- docs/python.rst
- src/schemathesis/models.py
- src/schemathesis/schemas.py
- src/schemathesis/specs/openapi/checks.py
- src/schemathesis/specs/openapi/schemas.py
- test/runner/test_checks.py
A part of #485, but without automatic endpoint detection.
TODO:
> feat: Shortcut for response validation when Schemathesis's data generation is not used

- docs/changelog.rst
- src/schemathesis/specs/openapi/checks.py
- src/schemathesis/specs/openapi/schemas.py
- test/runner/test_checks.py
> fix: Response conformance check for responses without "Content-Type" header

- docs/changelog.rst
- src/schemathesis/cli/callbacks.py
- test/cli/test_callbacks.py
> fix: Catch `OverflowError` in input regex validation

- .pylintrc
- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/loaders.py
- src/schemathesis/runner/__init__.py
- test/cli/test_commands.py
- test/test_loaders.py
It forces Schemathesis to use the specific Open API spec version when parsing the schema
Closes #876
> feat: `--force-schema-version` CLI option

- docs/changelog.rst
- src/schemathesis/exceptions.py
- src/schemathesis/specs/openapi/checks.py
- src/schemathesis/utils.py
- test/runner/test_checks.py
> chore: The `content_type_conformance` check now raises a well-formed error message when encounters a malformed media type value

- docs/changelog.rst
- src/schemathesis/specs/openapi/examples.py
- test/specs/openapi/test_examples.py
> fix: Internal error during verifying explicit examples if an example has no `value` key

- docs/changelog.rst
- src/schemathesis/runner/__init__.py
- test/cli/test_commands.py
> fix: Use `--request-tls-verify` during schema loading as well

- test/test_dereferencing.py
- test/test_petstore.py
It ensures that values are actually generated. Otherwise, some test branches may not be executed
> test: Use `assume` in some pytester-style tests

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- test/conftest.py
> fix: CLI failure if the tested operation is `GET` and has payload examples

- .github/workflows/codeql-analysis.yml
Now there is a warning:
> 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
This PR should solve it
> ci: Remove deprecated `git checkout HEAD^2` step from the CodeQL job

- docs/changelog.rst
- src/schemathesis/runner/impl/core.py
- test/cli/test_commands.py
> fix: `--exitfirst` CLI option trims the progress bar output when a failure occurs

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- test/runner/test_runner.py
> fix: Internal error if filling missing explicit examples led to `Unsatisfiable` errors

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- test/runner/test_runner.py
> fix: Skip explicit examples generation if this phase is disabled via config

- src/schemathesis/runner/impl/core.py
- test/runner/test_runner.py
Forgot to implement it in #976 
Ref: #975
> chore: Deduplicate collected errors that don't come from failed checks

- src/schemathesis/specs/openapi/references.py
- src/schemathesis/specs/openapi/schemas.py
- test/specs/openapi/test_security.py
- test/test_dereferencing.py
- test/test_parameters.py
- test/test_schemas.py
Regression after parameter parsing refactoring - such parameters were converted to `anyOf` schemas and cause a `KeyError` during parsing.
> fix: Collecting nullable parameters that are behind references

- docs/changelog.rst
- src/schemathesis/specs/openapi/examples.py
- test/specs/openapi/test_examples.py
> fix: Invalid types in `x-examples`

- docs/changelog.rst
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/runner/serialization.py
- src/schemathesis/schemas.py
- test/cli/output/test_default.py
Fixes #987 
However, this PR doesn't change the multi-worker implementation, it still significantly reduces memory usage:
- There is no peak during the initialization. Before a list of all endpoints was created - now it iterates over all endpoints.
- `endpoint` is not stored inside the test results, so it can be garbage collected during the run
> perf: Decrease memory usage

- docs/changelog.rst
- src/schemathesis/cli/output/default.py
- test/cli/output/test_default.py
- test/cli/test_commands.py
> fix: CLI crash on schemas with operation names longer than the current terminal width

- CONTRIBUTING.rst
- docs/changelog.rst
- src/schemathesis/models.py
- src/schemathesis/schemas.py
- test/apps/_aiohttp/handlers.py
- test/apps/_flask/__init__.py
- test/apps/utils.py
- test/cli/test_cassettes.py
- test/cli/test_commands.py
- test/runner/test_runner.py
- test/test_models.py
> fix: Handling of API operations that contain reserved characters in their paths

- docs/changelog.rst
- src/schemathesis/specs/openapi/schemas.py
- test/test_common_parameters.py
> fix: Processing parameters common for multiple API operations if they are behind a reference

- docs/changelog.rst
- src/schemathesis/specs/openapi/schemas.py
- test/test_common_parameters.py
> fix: Generating stateful tests, with common parameters behind a reference

- docs/changelog.rst
- src/schemathesis/specs/openapi/links.py
- test/test_stateful.py
The problem is triggered when schema validation is disabled and response status codes are noted as integers
Fixes #1022
> fix: Programmatic addition of Open API links via `add_link`

- docs/changelog.rst
- src/schemathesis/cli/output/default.py
- test/cli/output/test_default.py
CircleCI returns a zero-width terminal which was causing the schemathesis CLI to crash during jobs. Providing a default prevents crashing in these cases.
The default terminal size of 80w 24h was chosen because it seems to be a historically 'standard' terminal size.
Ref: (https://softwareengineering.stackexchange.com/questions/148754/why-is-24-lines-a-common-default-terminal-height)
> fix: Return a default terminal size to prevent crashes on systems with zero-width terminals

- docs/changelog.rst
- src/schemathesis/cli/output/default.py
Hello again!
Sorry, the fix that I implemented yesterday didn't work because I misunderstood how the `fallback` parameter of `shutil.get_terminal_size` worked. That value is only used if a terminal doesn't report a terminal size, but some CI/CD providers (like ours) DO provide a terminal size, it's just 0.
This fix will guarantee that a minimum terminal width of 80 is returned and I have tested this on our CI provider.
> fix: Return a minimum terminal width to prevent crashes on systems with zero-width terminals

- docs/changelog.rst
- src/schemathesis/specs/openapi/_hypothesis.py
- test/test_hypothesis.py
Avoid resolving relative paths and changing the tested path structure.
Fixes #1036
> fix: Percent-encode `.` and `..` strings in path parameters

- docs/changelog.rst
- src/schemathesis/cli/output/default.py
- src/schemathesis/runner/__init__.py
- src/schemathesis/runner/events.py
- src/schemathesis/runner/impl/core.py
- test-corpus/test_corpus.py
- test/cli/test_commands.py
- test/runner/test_runner.py
Passing `False` will skip some calculations which may significantly improve performance.
> feat: Add `count_operations` flag to `runner.prepare`

- docs/changelog.rst
- src/schemathesis/runner/impl/core.py
- test/runner/test_runner.py
> fix: Wrong test results in some cases when the tested schema contains a media type that Schemathesis doesn't know how to work with

- src/schemathesis/cli/handlers.py
- src/schemathesis/cli/output/default.py
- src/schemathesis/models.py
- src/schemathesis/runner/serialization.py
- test/cli/output/test_default.py
They are practically never optional
> chore(internal): Make `SerializedCheck.example` and `Check.example` not optional

- CONTRIBUTING.rst
- docs/changelog.rst
- src/schemathesis/cli/output/default.py
- src/schemathesis/models.py
- src/schemathesis/runner/serialization.py
- test/apps/_aiohttp/handlers.py
- test/apps/_flask/__init__.py
- test/apps/utils.py
- test/cli/output/test_default.py
- test/cli/test_commands.py
- test/runner/test_runner.py
> fix: Displaying wrong headers in the `FAILURES` block of the CLI output

- docs/changelog.rst
- src/schemathesis/specs/openapi/links.py
- test/specs/openapi/test_links.py
> fix: Missing `body` parameters during Open API links processing in CLI

- docs/changelog.rst
- src/schemathesis/runner/impl/threadpool.py
> chore: Prefix worker thread names with `schemathesis_`

- docs/changelog.rst
- poetry.lock
- pyproject.toml
Ref: https://github.com/python/importlib_metadata/issues/293
> fix(deps): Do not use `importlib-metadata==3.8` in dependencies

- docs/changelog.rst
- docs/compatibility.rst
- docs/faq.rst
Replace "fastapi" with "fast_api", since that is the name of the fixup module.
- [-] Created tests which fail without the change (if possible)
- [/] All tests passing, pylint and mypy fail; pytest and commitsar pass
- [+] Added a changelog entry
- [+] Extended the README / documentation, if necessary
> docs: use functioning fixup name in example

- src/schemathesis/specs/graphql/schemas.py
It is a required step to make GraphQL tests work via Schemathesis runner
> chore: Add blank impl for `GraphQLSchema.get_stateful_tests`

- docs/changelog.rst
- src/schemathesis/lazy.py
- test/test_lazy.py
> fix: Using parametrized `pytest` fixtures with the `from_pytest_fixture` loader

- docs/changelog.rst
- src/schemathesis/serializers.py
- test/runner/test_runner.py
> fix: `UnicodeEncodeError` when sending `application/octet-stream` payloads that have no `format: binary` in their schemas

- docs/changelog.rst
- docs/cli.rst
- src/schemathesis/cli/__init__.py
- test/cli/test_commands.py
> feat: Support for disabling ANSI color escape codes via the `NO_COLOR` environment variable or the `--no-color` CLI option

- docs/changelog.rst
- src/schemathesis/checks.py
- src/schemathesis/exceptions.py
It improves the variance of found errors.
> chore: Use different exception classes for `not_a_server_error` and `status_code_conformance` checks.

- docs/changelog.rst
- src/schemathesis/specs/openapi/_hypothesis.py
- src/schemathesis/specs/openapi/utils.py
- test/specs/openapi/test_hypothesis.py
It slightly improves the data generation performance - around 15% on the built-in `/headers/` API operation, and ~5% when running schemathesis against all operations in the built-in test server.
> perf: Reduce the amount of filtering needed to generate valid headers and cookies

- docs/changelog.rst
- src/schemathesis/specs/openapi/_hypothesis.py
- test/specs/openapi/test_hypothesis.py
In the first PR I missed that filtering still a problem when other keywords are present in headers' schemas
Ref: #1189
> fix: Disable filtering optimization for headers when there are keywords other than `type`

- docs/changelog.rst
- src/schemathesis/specs/openapi/examples.py
- test/specs/openapi/test_serializing.py
> fix: Apply the Open API's `style` & `explode` keywords to explicit examples

- docs/changelog.rst
- src/schemathesis/exceptions.py
- src/schemathesis/extra/pytest_plugin.py
- src/schemathesis/schemas.py
- src/schemathesis/utils.py
- test/hooks/test_hooks.py
- test/test_pytest.py
> chore: Raise `UsageError` if `schema.parametrize` or `schema.given` are applied to the same function more than once

- docs/changelog.rst
- src/schemathesis/specs/openapi/_hypothesis.py
- src/schemathesis/specs/openapi/serialization.py
- src/schemathesis/utils.py
- test/specs/openapi/test_hypothesis.py
- test/test_dereferencing.py
- test/test_hypothesis.py
> chore: Python values of `True`, `False` and `None` are converted to their JSON equivalents when generated for path parameters or query

- docs/changelog.rst
- src/schemathesis/runner/impl/core.py
- test/runner/test_runner.py
> feat: A way to stop the Schemathesis runner's event stream manually via `events.stop()`

- docs/changelog.rst
- src/schemathesis/cli/handlers.py
- test/apps/openapi/_aiohttp/handlers.py
- test/apps/openapi/_flask/__init__.py
- test/apps/openapi/schema.py
- test/cli/test_commands.py
> fix: Incorrect deduplication applied to response schema conformance failures that happen to have the same failing validator but different input values

- docs/changelog.rst
- src/schemathesis/specs/openapi/schemas.py
- test/runner/test_checks.py
> fix: `KeyError` when the `response_schema_conformance` check is executed against responses without schema definition

- docs/changelog.rst
- src/schemathesis/specs/openapi/links.py
- test/specs/openapi/test_links.py
> chore: Check non-string response statuses when Open API links are collected

- .rstcheck.cfg
- docs/changelog.rst
- docs/cli.rst
- docs/extending.rst
- docs/python.rst
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/utils.py
- test/test_pytest.py
> fix: Properly report all failures when custom checks are passed to `case.validate_response`

- docs/changelog.rst
- src/schemathesis/specs/openapi/loaders.py
- test/test_pytest.py
> chore:  Open API schema loaders now accept single `DataGenerationMethod` instances for the `data_generation_methods` argument

- docs/changelog.rst
- src/schemathesis/constants.py
- test/cli/output/test_default.py
- test/cli/test_commands.py
- test/runner/test_checks.py
- test/specs/openapi/test_stateful.py
- test/test_models.py
> chore: Show `cURL` code samples by default instead of Python

- src/schemathesis/specs/openapi/negative/mutations.py
It gives ~30% improvement for `ANY_TYPE_KEYS` and >320% for `ALL_KEYWORDS` on my test data. Though, the improvement is limited only to `split_schema` and `drop_not_type_specific_keywords` which are called pretty often
> perf: Use sets during negative testing data generation

- docs/changelog.rst
- src/schemathesis/models.py
- test/code_samples/test_python.py
> fix: Unescaped quotes in generated Python code samples on some schemas

- .github/workflows/release.yml
Changed the Docker image for release-notary. 
Reasoning:
Outillage has been deprecated in favour of aevea. There is full compatibility as until now the outillage branch has been released as well.
> chore: update release notary

- docs/changelog.rst
- src/schemathesis/runner/impl/core.py
- test/conftest.py
- test/runner/test_runner.py
> fix: Handle `KeyboardInterrupt` that happens outside of the main test loop inside the runner

- docs/changelog.rst
- src/schemathesis/lazy.py
- src/schemathesis/schemas.py
- src/schemathesis/specs/openapi/loaders.py
- test/test_lazy.py
> fix: Respect the `data_generation_methods` config option defined on a schema instance when it is loaded via `from_pytest_fixture`

- docs/changelog.rst
- src/schemathesis/lazy.py
- test/test_lazy.py
It allows the end-user to disambiguate among subtest reports
> chore: Use `name` & `data_generation_method` parameters to subtest context instead of `path` & `method`

- docs/changelog.rst
- src/schemathesis/constants.py
- src/schemathesis/extra/pytest_plugin.py
- test/test_filters.py
> chore: Raise an error if a test function wrapped with `schema.parametrize` matches no API operations

- docs/changelog.rst
- src/schemathesis/hooks.py
- src/schemathesis/lazy.py
- test/test_lazy.py
> fix: Ignored hooks defined on a schema instance when it is loaded via `from_pytest_fixture`

- docs/changelog.rst
- src/schemathesis/specs/openapi/loaders.py
- src/schemathesis/specs/openapi/validation.py
- test/loaders/test_openapi.py
> fix: Silently failing to detect numeric status codes when the schema contains a shared `parameters` key

- docs/changelog.rst
- poetry.lock
- pyproject.toml
Loosen the requirement to allow versions above 4. Set a limit on <5 to
prevent issues when/if breaking changes occurs.
Rebuilt lock-file with `poetry lock`
Close #1365
> Update typing-extensions requirement to allow >4

- docs/changelog.rst
- src/schemathesis/models.py
- test/runner/test_runner.py
- test/test_asgi.py
> fix: Improper handling of `base_url` in `call_asgi`, when the base URL has a non-empty base path

- docs/changelog.rst
- src/schemathesis/specs/openapi/_hypothesis.py
- test/test_hypothesis.py
> fix: Generating illegal unicode surrogates in queries #1370

- example/Dockerfile
- example/README.rst
- example/docker-compose.yml
- example/test/test_app.py
Simplified and stabilized docker-related stuff in `example` dir:
1. removed unused deb-packages which were needed to build some old `asyng` wheels
2. binded web app port to `127.0.0.1` instead of `0.0.0.0` , it's more secure
3. added option to recreate web app container on failure, it helps to start web app in robust way
4. fixed depended docker image version to `postgres:14`, the current one
5. mounted `main.py` to containter (run-time dependency) instead of copying it (build-time dependency)
> Update example docker files

- docs/changelog.rst
- docs/python.rst
- src/schemathesis/models.py
- test/test_models.py
> chore: Validate `requests` kwargs to catch cases when the ASGI integration is used, but the proper ASGI client is not supplied

- docs/changelog.rst
- docs/service.rst
- poetry.lock
- pyproject.toml
- src/schemathesis/cli/__init__.py
- src/schemathesis/service/__init__.py
- src/schemathesis/service/constants.py
- src/schemathesis/service/hosts.py
- test/cli/test_commands.py
- test/conftest.py
- test/service/test_auth.py
Token is not used yet for the SaaS integration
> feat: Add a command to authenticate with Schemathesis.io

- .pre-commit-config.yaml
- docs/requirements.txt
- docs/service.rst
It fixes an incompatibility with the recent Jinja release
> fix(docs): Bump Sphinx version

- docs/changelog.rst
- src/schemathesis/_compat.py
- src/schemathesis/utils.py
> chore: Support for `Hypothesis>=6.41.0`

- docs/changelog.rst
- src/schemathesis/models.py
- test/test_models.py
It led to missing payload in failure reproduction code samples
> fix: Missing `media_type` in the `Case.partial_deepcopy` implementation.

- docs/changelog.rst
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/utils.py
- test/test_models.py
> fix: Missing `source` attribute in the `Case.partial_deepcopy` implementation

- docs/changelog.rst
- src/schemathesis/exceptions.py
- src/schemathesis/failures.py
- src/schemathesis/models.py
- src/schemathesis/runner/serialization.py
- src/schemathesis/specs/openapi/checks.py
- test/runner/test_checks.py
- test/test_models.py
> fix: Duplicated failure message from `content_type_conformance` and `response_schema_conformance` checks

- docs/changelog.rst
- src/schemathesis/lazy.py
- test/test_lazy.py
> fix: Ignored `pytest.mark` decorators when they are applied before `schema.parametrize` if the schema is created via `from_pytest_fixture`

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/context.py
- src/schemathesis/cli/options.py
- src/schemathesis/cli/output/default.py
- src/schemathesis/constants.py
- src/schemathesis/runner/__init__.py
- test/cli/output/test_default.py
- test/cli/test_commands.py
Resolves #1326 
Resolves #1445
> Configure Hypothesis db

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/callbacks.py
- src/schemathesis/service/__init__.py
- src/schemathesis/service/client.py
- src/schemathesis/service/models.py
- test/cli/test_callbacks.py
- test/cli/test_commands.py
- test/service/conftest.py
- test/service/test_cli.py
The main idea is to enable people to run `st run slug` where "slug" is a shortcut name for an API in Schemathesis.io, so the actual schema address could be loaded from there.
It would be nice to avoid calling the service for API config before validating the "api_slug" argument - maybe assume that if `SCHEMA` is not an URL / path, then it is always a slug, then just throw an error if `api_slug` is present?
TODO:
> feat: Make the `SCHEMA` CLI argument accept API slug from Schemathesis.io

- .github/workflows/build.yml
- docs/changelog.rst
- poetry.lock
- pyproject.toml
- src/schemathesis/constants.py
- src/schemathesis/extra/pytest_plugin.py
- test/test_app.py
- test/test_pytest.py
- tox.ini
That is an ugly hack for now :(
TODO:
> fix: Compatibility with `pytest>=7.0`

- docs/changelog.rst
- docs/cli.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/callbacks.py
- src/schemathesis/cli/cassettes.py
- src/schemathesis/models.py
- test/cli/test_cassettes.py
- test/cli/test_commands.py
> feat: Do not encode payloads in cassettes as base64 by default

- docs/changelog.rst
- poetry.lock
- pyproject.toml
- src/schemathesis/specs/openapi/schemas.py
> fix: Internal error inside `BaseOpenAPISchema.validate_response` on `requests>=2.27` when response body contains malformed JSON

- pyproject.toml
This pr fixes schemathesis editable installation via pip. Quite useful for local hacking i believe. :) 
Poetry-core implements PEP660 from version 1.0.8.
For more info see:
- https://github.com/python-poetry/poetry/issues/34#issuecomment-1054626460
- https://github.com/python-poetry/poetry/issues/5056
- https://github.com/python-poetry/poetry-core/pull/257
> Fix editable installation

- docs/changelog.rst
- src/schemathesis/extra/pytest_plugin.py
- test/test_pytest.py
> fix: Do not re-raise `InvalidArgument` exception as `InvalidSchema` in non-Schemathesis tests

- docs/changelog.rst
- src/schemathesis/specs/openapi/expressions/parser.py
- test/specs/openapi/test_expressions.py
Allow dots in OpenAPI expressions outside variable definitions. Currently, the parser discards these dots. With this PR, the parser outputs dots as strings.
[Postgrest horizontal filtering via query parameters](https://postgrest.org/en/stable/api.html#horizontal-filtering-rows):
```
GET /people?age=lt.13
GET /people?age=gte.18&student=is.true
GET /users?id=eq.42
```
OpenAPI links to these operations require the dot. E.g., `eq.{$response.body#/0/id}`. Currently, schemathesis outputs `id=eq42` that fails because of the missing dot. With this PR, the same expression outputs `id=eq.42` that works.
- [Y] Created tests which fail without the change (if possible)
- [Y] All tests passing
- [Y] Added a changelog entry
- [N/A] Extended the README / documentation, if necessary
> fix: Do not discard dots in OpenAPI expressions during parsing

- .github/workflows/build.yml
- docs/changelog.rst
- poetry.lock
- src/schemathesis/_compat.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/utils.py
- test/specs/openapi/test_serializing.py
- test/test_lazy.py
- tox.ini
> fix: Compatibility with `hypothesis>=6.49`

- docs/changelog.rst
- src/schemathesis/specs/openapi/checks.py
- src/schemathesis/specs/openapi/schemas.py
- test/apps/openapi/schema.py
- test/runner/test_checks.py
Open API 2.0 headers do not support `required`, so use `x-required` instead (as this approach is already used for other cases like `nullable` & `example`)
> fix: Do not report optional headers as missing

- pyproject.toml
- src/schemathesis/runner/events.py
Hi,
this PR replaces manually configured options for `isort` with `profile=black` clause which does the same automatically, see https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
There's also a typo fixed, but it didnt feel like it's worth creating a separate commit for it.
> misc: use black profile for isort

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- test/cli/test_commands.py
I've noticed this line in the docs (generated from the help message)
```
-v, --verbosity Reduce verbosity of error output.
```
because usually it works the other way. After a brief check, I see that indeed MORE information is displayed when `-v` option is provided.
> fix: verbosity help message

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/hooks.py
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- test/cli/test_hooks.py
It makes them available for the `pytest` integration
> chore: Execute `before_call` / `after_call` hooks inside the `call_*` methods

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- test/cli/test_cassettes.py
> feat: Display old and new payloads in `st replay` when the `-v` option is passed.

- docs/changelog.rst
- src/schemathesis/specs/graphql/schemas.py
- test/specs/graphql/test_basic.py
> fix: Internal error when GraphQL schema has its root types renamed

- poetry.lock
- pyproject.toml
try to fix : https://github.com/schemathesis/schemathesis/issues/1614
> issue-1614/add-httpx-dependency

- tox.ini
Otherwise, `schemathesis` is not found on Windows
> test: Install schemathesis before running tests

- docs/changelog.rst
- poetry.lock
- pyproject.toml
- test/test_app.py
- test/test_parameters.py
This PR allows `schemathesis` to use `Werkzeug<=2.2.2`
Linked issue: https://github.com/schemathesis/schemathesis/issues/1631
> feat(deps): allow `Werkzeug<=2.2.2` dependency

- docs/changelog.rst
- src/schemathesis/runner/impl/core.py
- test/apps/openapi/_flask/__init__.py
- test/runner/test_runner.py
It also fixes a rare test failure in `test_hypothesis_failed_event`
> fix: Properly display flaky deadline errors

- docs/changelog.rst
- src/schemathesis/stateful.py
- test/specs/openapi/test_stateful.py
> fix: Printing header that are set explicitly via `get_call_kwargs` in stateful testing

- docs/changelog.rst
- src/schemathesis/specs/openapi/negative/mutations.py
On the example API the number of rejected cases dropped on average from thousands to dozens (for `--max-examples=10`)
> perf: Filter out less data during schema mutation

- docs/changelog.rst
- src/schemathesis/specs/openapi/loaders.py
- test/loaders/test_openapi.py
It improves schema loading time for common cases by using a faster JSON loader. For big schemas, performance win could be up to 30x.
> perf: Try a faster loader first if an HTTP response or a file is expected to be JSON

- docs/changelog.rst
- pyproject.toml
Mitigation of CVE-2023-25577 requires upgrading Werkzeug to 2.2.3. This PR loosens the dependency requirement to allow any Werkzeug 2.x as there doesn't appear to be a reason to be stricter.
This resolves #1695.
- n/a
- n/a
> Allow mitigation of CVE-2023-25577

- docs/auth.rst
- docs/changelog.rst
- src/schemathesis/auths.py
- src/schemathesis/filters.py
- src/schemathesis/lazy.py
- test/auth/test_cli.py
- test/auth/test_provider.py
- test/auth/test_pytest.py
- test/cli/test_commands.py
- test/conftest.py
- test/contrib/test_unique_data.py
- test/filters/test_matching.py
- test/hooks/test_hooks.py
- test/service/test_cli.py
- test/service/test_usage.py
> feat: Selective auth

- .pre-commit-config.yaml
- docs/changelog.rst
- pyproject.toml
Bump of allowed requests version to 2.28.2
> chore: bump allowed requests to 2.28.2

- docs/changelog.rst
- docs/cli.rst
- docs/python.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/models.py
- src/schemathesis/specs/graphql/schemas.py
- test/cli/test_checks.py
- test/cli/test_commands.py
- test/test_pytest.py
This feature allows users to pass a tuple of check functions that they want to be excluded. Exclusions are applied as a final step so adding an additional_check and excluding it will result in the check not being run.
> feat: add excluded_checks option

- .github/workflows/example-build.yml
> build: Do not test failing endpoints in `example-build`

- docs/changelog.rst
- src/schemathesis/specs/openapi/parameters.py
- test/auth/test_cli.py
> fix: `Unsatisfiable` error for multiple security schemes applied to the same API operation and an explicit `Authorization` header

- docs/changelog.rst
- src/schemathesis/auths.py
Fix the type hint for auths/AuthProvider (fixes #1776)
Did not see any tests/CI for mypy
> auths/AuthProvider: bind Generic to Auth

- docs/changelog.rst
- docs/extending.rst
- src/schemathesis/hooks.py
- src/schemathesis/models.py
- src/schemathesis/specs/openapi/_hypothesis.py
- test/hooks/test_hooks.py
Ref: #1673
Next steps:
- Deprecate `before_generate_` hooks (add warnings) + add equivalent `generate_` hooks
- Filters (`apply_to`, `skip_for`) + validation
- Error messages for hooks
> feat: Shortcuts for hooks

- src/schemathesis/auths.py
Add overloads for `__call__` to AuthProvider to fix mypy issue.
Fixes #1776
> fix: auths/AuthProvider: add overloads for __call__

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
> chore: Do not display `InsecureRequestWarning` in CLI output if the user explicitly provided `--request-tls-verify=false`

- .rstcheck.cfg
- docs/changelog.rst
- docs/cli.rst
- docs/compatibility.rst
- docs/contrib.rst
- docs/experimental.rst
- docs/faq.rst
- docs/index.rst
- docs/introduction.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/callbacks.py
- src/schemathesis/cli/output/default.py
- src/schemathesis/experimental/__init__.py
- src/schemathesis/specs/openapi/loaders.py
- src/schemathesis/specs/openapi/schemas.py
- test/cli/test_commands.py
- test/experimental/conftest.py
- test/experimental/test_experiments.py
- test/experimental/test_openapi_3_1.py
> feat: experimental support of OpenAPI 3.1

- docs/changelog.rst
- src/schemathesis/constants.py
- src/schemathesis/models.py
- src/schemathesis/runner/serialization.py
- src/schemathesis/utils.py
- test/code_samples/test_curl.py
> fix: Generated cURL commands now include the `Content-Type` header, which was previously omitted

- docs/changelog.rst
- pyproject.toml
- src/schemathesis/_compat.py
- src/schemathesis/models.py
> chore: Support `Werkzeug>=3.0`

- .github/workflows/build.yml
- docs/changelog.rst
- pyproject.toml
- tox.ini
Resolves #1809 
Run CI workflows against latest Python 3.12 beta (3.12b4 as of writing this PR), it gives an overall good idea of schemathesis compatibility with this Python version.
> chore(python): add Python 3.12 compatibility

- src/schemathesis/specs/openapi/schemas.py
- src/schemathesis/transports/responses.py
- test/conftest.py
- test/test_models.py
- test/transports/test_responses.py
🚨Please review the [Contributing Guidelines](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.rst).
Basic httpx support that allows to pass `httpx.Response` objects to OpeanAPI `validate_response` method.
> feat: Add basic httpx support for validate_response

- docs/changelog.rst
- docs/cli.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/cli/context.py
- src/schemathesis/cli/output/default.py
- test/auth/test_cli.py
- test/cli/__snapshots__/test_commands/test_get_request_with_body[Open API 2.0].raw
- test/cli/__snapshots__/test_commands/test_get_request_with_body[Open API 3.0].raw
- test/cli/__snapshots__/test_commands/test_run_output[args24].raw
- test/cli/__snapshots__/test_commands/test_unsatisfiable[real-Open API 2.0-1].raw
- test/cli/__snapshots__/test_commands/test_unsatisfiable[real-Open API 2.0-2].raw
- test/cli/__snapshots__/test_commands/test_unsatisfiable[real-Open API 3.0-1].raw
- test/cli/__snapshots__/test_commands/test_unsatisfiable[real-Open API 3.0-2].raw
- test/cli/__snapshots__/test_commands/test_unsatisfiable[wsgi-Open API 2.0-1].raw
- test/cli/__snapshots__/test_commands/test_unsatisfiable[wsgi-Open API 2.0-2].raw
- test/cli/__snapshots__/test_commands/test_unsatisfiable[wsgi-Open API 3.0-1].raw
- test/cli/__snapshots__/test_commands/test_unsatisfiable[wsgi-Open API 3.0-2].raw
- test/cli/__snapshots__/test_commands/test_unsupported_regex.raw
- test/cli/output/test_default.py
- test/cli/test_asgi.py
- test/cli/test_commands.py
> chore: Deprecate using the `--show-errors-tracebacks` CLI option

- docs/changelog.rst
- docs/contrib.rst
- docs/faq.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/cli/__init__.py
- src/schemathesis/contrib/openapi/__init__.py
- src/schemathesis/contrib/openapi/fill_missing_examples.py
- test/cli/__snapshots__/test_commands/test_run_output[args24].raw
- test/contrib/openapi/__snapshots__/test_fill_missing_examples/test_fills_missing_examples.raw
- test/contrib/openapi/test_fill_missing_examples.py
> feat: An option to generate random examples for API operations that lack explicit examples

- docs/changelog.rst
- src/schemathesis/specs/openapi/examples.py
- test/specs/openapi/test_examples.py
> fix: Not using `examples` from shared `parameters`

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- src/schemathesis/extra/pytest_plugin.py
- src/schemathesis/runner/impl/core.py
- test/runner/test_runner.py
- test/test_pytest.py
- tox.ini
> chore: Raise an error if it is not possible to generate explicit examples

- docs/changelog.rst
- src/schemathesis/specs/openapi/examples.py
- test/specs/openapi/test_examples.py
> fix: Ignoring examples referenced via the `$ref` keyword

- tox.ini
This way snapshots will use the proper width
> built: Set `COLUMNS=80` in tox build

- docs/changelog.rst
- docs/extending.rst
- src/schemathesis/specs/graphql/schemas.py
- test/hooks/test_hooks.py
> fix: Not calling hooks for `query` / `cookies` / `headers` in GraphQL schemas

- docs/changelog.rst
- src/schemathesis/checks.py
- src/schemathesis/specs/graphql/schemas.py
- src/schemathesis/specs/openapi/schemas.py
- src/schemathesis/transports/responses.py
- test/specs/graphql/test_basic.py
Currently call_and_validate doesn't check if in the graphql response are any errors or the answer is json at all.
This happened in my tests in my project.
This PR should fix the problem but I cannot test it.
It is really hard to contribute.
I don't understand in which test file I can define such a test and the test procedure fails for different sized terminals.
Sorry.
> fix: validate that the graphql response is valid

- docs/changelog.rst
- docs/python.rst
- src/schemathesis/constants.py
- src/schemathesis/extra/pytest_plugin.py
- test/test_pytest.py
> chore: Explicitly note that combining `@schema.given` with explicit examples from the spec is not supported

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- src/schemathesis/service/hosts.py
- src/schemathesis/utils.py
- test/cli/test_junitxml.py
> fix: Create parent directories when saving JUnit XML reports and other file-based output

- docs/changelog.rst
- src/schemathesis/cli/__init__.py
- test/cli/__snapshots__/test_commands/test_hooks_with_inner_import_error.raw
- test/cli/test_commands.py
> fix: Incorrect error message when the code inside the hook module raises `ImportError`

- docs/changelog.rst
- src/schemathesis/_hypothesis.py
- test/test_lazy.py
> fix: `InvalidArgument` when using `from_pytest_fixture` with parametrized pytest fixtures

- docs/changelog.rst
- src/schemathesis/specs/openapi/schemas.py
- test/specs/openapi/randomized/factory.py
- test/specs/openapi/randomized/test_randomized.py
- test/specs/openapi/randomized/types.py
- test/specs/openapi/randomized/v2.py
- test/specs/openapi/test_hypothesis.py
> test: Add tests with generated schemas

- docs/python.rst
Replace closing curly with closing brace to fix syntax in schema.override() example
> fix code typo in python docs

- docs/changelog.rst
- src/schemathesis/specs/openapi/examples.py
- src/schemathesis/specs/openapi/schemas.py
- test/specs/openapi/test_examples.py
- test/test_examples.py
> fix: Ignoring property examples defined under the `example` key in Open API 2.0 schemas

- docs/changelog.rst
- docs/graphql.rst
- pyproject.toml
- src/schemathesis/cli/__init__.py
- src/schemathesis/generation/__init__.py
- src/schemathesis/specs/graphql/schemas.py
- test/cli/__snapshots__/test_commands/test_run_output[args24].raw
- test/conftest.py
- test/specs/graphql/__snapshots__/test_basic/test_disallow_null.raw
- test/specs/graphql/test_basic.py
> feat: The `--generation-graphql-allow-null` CLI option that controls whether `null` should be used for optional arguments in GraphQL queries

- docs/changelog.rst
- src/schemathesis/specs/openapi/checks.py
- test/runner/test_checks.py
> fix: Error in `response_header_conformance` if the header definition is behind `$ref`

- docs/changelog.rst
- src/schemathesis/specs/openapi/definitions.py
- test/experimental/test_openapi_3_1.py
Fixes #2484 
Schemathesis uses static version of the current published version of the OpenApi 3.1 spec metaschema
(https://spec.openapis.org/oas/3.1/schema/2022-10-07) to validate openapi 3.1 spec documents. Unfortunately, the published version has at least one known bug in which the schema for `paths` references the definition of a concrete `path-item` instead of `path-item-or-reference`, which might still be technically incorrect when it comes handling the case of ref and sibling fields, but is correct according to the documented definition of a pathItemObject.
This oversight has been noticed multiple times
https://github.com/OAI/OpenAPI-Specification/issues/3298 https://github.com/OAI/OpenAPI-Specification/issues/2635#issuecomment-960248801 …
> fix(oas3.1): correctly validate paths using $ref

- src/schemathesis/constants.py
- src/schemathesis/models.py
- src/schemathesis/pytest/plugin.py
- src/schemathesis/runner/phases/unit/_executor.py
- src/schemathesis/schemas.py
- src/schemathesis/specs/openapi/schemas.py
- src/schemathesis/stateful/validation.py
- test/cli/__snapshots__/test_commands/test_useful_traceback[Open API 3.0].raw
- test/runner/test_runner.py
- test/test_models.py
- Removed `partial_deepcopy`, assuming `Case` is not mutated within a check
> refactor: Simplify cloning

- docs/changelog.rst
- src/schemathesis/internal/checks.py
- src/schemathesis/models.py
- src/schemathesis/runner/impl/core.py
- src/schemathesis/specs/graphql/schemas.py
- src/schemathesis/specs/openapi/checks.py
- test/specs/openapi/test_ignored_auth.py
> fix: Ignore request-related configuration inside the ignored_auth check

- docs/changelog.rst
- src/schemathesis/engine/phases/stateful/_executor.py
- src/schemathesis/generation/stateful/state_machine.py
- test/specs/openapi/stateful/test_stateful.py
Fixes #2713.
Will backport separately and without a breaking change (probably via a private attribute on the state machine instance)
> fix: Ignoring verify=False when specified via get_call_kwargs on a state machine

- CHANGELOG.md
- src/schemathesis/generation/hypothesis/builder.py
- src/schemathesis/specs/openapi/schemas.py
- test/fixtures/ctx.py
- test/test_serialization.py
> fix: Missing reference resolution scope when serializing `multipart` payloads

- src/schemathesis/cli/commands/run/executor.py
It improves process interruption handling for cases when interrupted while starting handlers.
In this implementation, the handlers aren't going to be `shutdown()` in case of `click.Abort` interruption. I keep this part of logic as is, because changing it would affect the responsiveness from the user perspective.
But I think that a more graceful shutdown might make sense, so if you want this, please let me know and I will update the patch.
> fix: Improve process interruption handling, for cases when interrupted while starting handlers

- CHANGELOG.md
- src/schemathesis/core/transport.py
- src/schemathesis/generation/case.py
- src/schemathesis/schemas.py
- test/conftest.py
- test/python/test_models.py
> feat: Support for validating `requests` / `httpx` / `werkzeug` responses in `Case.validate_response`

- CHANGELOG.md
- src/schemathesis/transport/prepare.py
- src/schemathesis/transport/requests.py
- src/schemathesis/transport/wsgi.py
- test/specs/openapi/test_checks.py
> fix: Do not send explicitly passed headers for the `missing_required_header` check

- CHANGELOG.md
- src/schemathesis/generation/stateful/state_machine.py
- test/specs/openapi/stateful/__snapshots__/test_cli/test_unique_inputs.raw
- test/specs/openapi/stateful/test_cli.py
> fix: Internal error if the stateful phase is used with `--generation-unique-inputs`

- CHANGELOG.md
- src/schemathesis/generation/coverage.py
- test/coverage/test_combinations.py
> fix: Generating negative test cases incorrectly marked as invalid if `anyOf` is present

- CHANGELOG.md
- src/schemathesis/specs/openapi/_hypothesis.py
- test/specs/openapi/__snapshots__/test_examples/test_path_parameters_example_escaping.raw
- test/specs/openapi/test_examples.py
> fix: Escape examples for path parameters

- CHANGELOG.md
- src/schemathesis/generation/coverage.py
🚨Please review the [Contributing Guidelines](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.md).
Non-functional changes that allows schemathesis to run under pypy3. In short, uses the documented python api for iterative encoding. 
Unfortunately, there's no speedup using pypy, but this is an easy win for people who really want to use pypy.
> Make coverage.py compatible with pypy3

- CHANGELOG.md
- src/schemathesis/generation/hypothesis/builder.py
- src/schemathesis/specs/openapi/_hypothesis.py
- src/schemathesis/specs/openapi/adapter/__init__.py
- src/schemathesis/specs/openapi/adapter/protocol.py
- src/schemathesis/specs/openapi/adapter/responses.py
- src/schemathesis/specs/openapi/adapter/v3_0.py
- src/schemathesis/specs/openapi/adapter/v3_1.py
- src/schemathesis/specs/openapi/checks.py
- src/schemathesis/specs/openapi/schemas.py
- test/coverage/test_phase.py
note: changelog entry covers previous improvements (caching schema transformation, fewer clones, skipping `RefResolver` construction, etc)
> perf: Cache response validators
